package content

import "testing"

func TestIsGeneratedCodeLine_Go(t *testing.T) {
	cases := []struct {
		line string
		want bool
	}{
		// Official Go convention.
		{"// Code generated by protoc-gen-go. DO NOT EDIT.", true},
		// Mockery / easyjson variants without the canonical suffix.
		{"// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.", true},
		{"// Code generated by mockery. DO NOT EDIT.", true},
		// Case-insensitive — lowercase substring match.
		{"// CODE GENERATED BY some_tool. DO NOT EDIT.", true},
		// Real human-written code with the word "generated" elsewhere should NOT fire.
		{"// generated a random id for the request", false},
		{"package main", false},
		{"func GenerateRandomID() string { return \"\" }", false},
	}
	for _, tc := range cases {
		t.Run(tc.line, func(t *testing.T) {
			if got := isGeneratedCodeLine(tc.line, "go"); got != tc.want {
				t.Errorf("got %v, want %v", got, tc.want)
			}
		})
	}
}

func TestIsGeneratedCodeLine_Python(t *testing.T) {
	for line, want := range map[string]bool{
		"# Generated by the protocol buffer compiler.  DO NOT EDIT!": true,
		"# This file is autogenerated by foo.":                       true,
		"# @generated":                                               true,
		"def hello():":                                                false,
		"# Regular comment about generated content":                  false,
	} {
		if got := isGeneratedCodeLine(line, "python"); got != want {
			t.Errorf("python line %q → %v, want %v", line, got, want)
		}
	}
}

func TestIsGeneratedCodeLine_CSharp(t *testing.T) {
	if !isGeneratedCodeLine("// <auto-generated>", "csharp") {
		t.Error("csharp auto-generated header should fire")
	}
	if !isGeneratedCodeLine("//------------------------------------------------------------------------------\n// <auto-generated>", "csharp") {
		// Wider real-world MS-shape; the substring still matches.
		t.Error("csharp wide auto-generated header should fire")
	}
}

func TestIsGeneratedCodeLine_AtGeneratedAcrossLanguages(t *testing.T) {
	// The @generated annotation — Facebook's cross-language convention —
	// fires in every language that honours it.
	for _, lang := range []string{"javascript", "typescript", "rust", "php", "java", "kotlin", "scala"} {
		if !isGeneratedCodeLine("// @generated", lang) {
			t.Errorf("@generated should fire for %q", lang)
		}
	}
	// Ruby / Python use # comments, so the JS-shape doesn't fire.
	for _, lang := range []string{"ruby", "python"} {
		if isGeneratedCodeLine("// @generated", lang) {
			t.Errorf("// @generated should NOT fire for %q (different comment syntax)", lang)
		}
	}
	// Shell + ruby + python honour the # variant.
	for _, lang := range []string{"shell", "ruby", "python"} {
		if !isGeneratedCodeLine("# @generated", lang) {
			t.Errorf("# @generated should fire for %q", lang)
		}
	}
}

func TestIsGeneratedCodeLine_UnknownLanguage(t *testing.T) {
	// Languages without registered markers always return false.
	for _, lang := range []string{"", "brainfuck", "haskell", "ocaml"} {
		if isGeneratedCodeLine("// generated by", lang) {
			t.Errorf("%q has no registered markers; should return false", lang)
		}
	}
}
