package content

import "strings"

// Generated-code detection. A file's first ~20 lines are checked
// against a per-language set of header markers; one hit sets the
// is_generated_code CEL attribute. Markers are substrings (lowercased
// match) because the dominant conventions are tool-generated comment
// preambles, not regex-shaped patterns, and we want the detection to
// stay cheap (~one strings.Contains per line per pattern).
//
// Sources for the patterns: the Go toolchain's official `// Code
// generated ... DO NOT EDIT.` convention (cmd/go/internal/generate),
// protoc's per-language headers, Microsoft's <auto-generated> shape
// for C#, the `@generated` annotation popular across JS / TS / Rust /
// PHP via Facebook's coding-style convention, and the universal
// "DO NOT EDIT" / "Generated by" prefixes the rest of the ecosystem
// converged on. Issue #276.

// generatedMarkers maps the bare language name (without the "source/"
// prefix) to header substrings. Each substring is matched against the
// line lowercased so callers don't have to write case-insensitive
// regex. Empty for languages without an established convention —
// is_generated_code stays false for them rather than guessing.
var generatedMarkers = map[string][]string{
	"go": {
		// Official convention from cmd/go/internal/generate. The
		// trailing "DO NOT EDIT." is mandatory in the spec but we
		// match only the leading marker so protoc-gen-go / mockery /
		// etc. variants without the canonical suffix also fire.
		"// code generated ",
	},
	"python": {
		"# generated by",
		"# generated automatically",
		"# autogenerated",
		"# this file is autogenerated",
		"# do not edit",
		"# @generated",
	},
	"java": {
		"// generated by",
		"@javax.annotation.generated",
		"@generated",
		"// do not edit",
	},
	"kotlin": {
		"// generated by",
		"@generated",
		"// do not edit",
	},
	"scala": {
		"// generated by",
		"// do not edit",
		"@generated",
	},
	"csharp": {
		// Microsoft's official auto-generated XML comment used by every
		// .NET source generator. The closing `>` may have whitespace
		// variants; a substring check on the open is enough.
		"// <auto-generated",
		"<auto-generated>",
		"// generated by",
		"// do not edit",
	},
	"javascript": {
		"// @generated",
		"// this file is auto-generated",
		"// do not edit",
		"// generated by",
	},
	"typescript": {
		"// @generated",
		"// this file is auto-generated",
		"// do not edit",
		"// generated by",
	},
	"rust": {
		"// @generated",
		"// auto-generated",
		"// generated by",
		"// do not edit",
	},
	"ruby": {
		"# @generated",
		"# generated by",
		"# do not edit",
	},
	"swift": {
		"// generated by",
		"// do not edit",
		"// @generated",
	},
	"perl": {
		"# generated by",
		"# do not edit",
	},
	"shell": {
		"# generated by",
		"# do not edit",
		"# @generated",
	},
	"php": {
		"// @generated",
		"// generated by",
		"// do not edit",
		"# generated by",
	},
}

// isGeneratedCodeLine reports whether the given line (after the
// scanner's already-trimmed-whitespace normalisation) carries a known
// generator marker for language. Lowercased substring match against
// generatedMarkers[language]. Returns false for languages without a
// registered convention OR when no marker pattern is present in the
// line.
func isGeneratedCodeLine(line, language string) bool {
	markers := generatedMarkers[language]
	if len(markers) == 0 {
		return false
	}
	lower := strings.ToLower(line)
	for _, m := range markers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	return false
}

// generatedCodeLineBudget caps how many leading lines the source-type
// scanner checks for the generator marker. 20 is comfortably past the
// "copyright header THEN generator marker" shape that some tools emit
// (a typical license header is 6-12 lines + a blank + the marker on
// line ~14). Lines past the budget are skipped to keep the per-file
// cost negligible.
const generatedCodeLineBudget = 20
