package celexpr

// AttributeDoc describes a single CEL attribute available in expressions.
type AttributeDoc struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// FunctionDoc describes a CEL-callable function registered on the
// environment. Unlike attributes, functions have a signature (the formal
// argument list and return type), so the schema needs a richer doc type.
type FunctionDoc struct {
	Name        string `json:"name"`
	Signature   string `json:"signature"`
	Description string `json:"description"`
	Example     string `json:"example,omitempty"`
}

// SchemaDoc groups the documented CEL attributes by category, plus the
// callable built-in functions registered on the environment.
type SchemaDoc struct {
	Common       []AttributeDoc `json:"common"`
	TypeSpecific []AttributeDoc `json:"type_specific"`
	Frontmatter  []AttributeDoc `json:"frontmatter"`
	Functions    []FunctionDoc  `json:"functions"`
}

// Schema returns the structured documentation for every CEL attribute
// and function the evaluator declares. Both the CLI's --list output and
// the MCP list_attributes tool format their output from this.
func Schema() SchemaDoc {
	return SchemaDoc{
		Common: []AttributeDoc{
			{"name", "string", "filename"},
			{"path", "string", "full path"},
			{"dir", "string", "parent directory"},
			{"size", "int", "file size in bytes"},
			{"ext", "string", "file extension (e.g. '.md')"},
			{"content_type", "string", "detected content type"},
			{"is_markdown", "bool", "true if markdown file"},
			{"is_json", "bool", "true if JSON file (.json + package.json/package-lock.json which also fire is_node_manifest)"},
			{"is_xml", "bool", "true if XML file"},
			{"is_html", "bool", "true if HTML file"},
			{"is_pdf", "bool", "true if PDF file"},
			{"is_image", "bool", "true if image file"},
			{"is_text", "bool", "true if plain-text file (.txt, .text, .log) — also fires for requirements.txt, LICENSE, CHANGELOG, CONTRIBUTING which are plain text by convention"},
			{"is_csv", "bool", "true if CSV/TSV file"},
			{"is_epub", "bool", "true if EPUB book"},
			{"is_office", "bool", "true if office document (DOCX, XLSX, PPTX, ODT — content_type starts with 'office/')"},
			{"is_audio", "bool", "true if audio file (MP3, M4A, FLAC, OGG — content_type starts with 'audio/')"},
			{"is_video", "bool", "true if video file (MP4, MOV, MKV, WebM, AVI — content_type starts with 'video/')"},
			{"is_archive", "bool", "true if archive file (ZIP, TAR, TAR.GZ, GZIP — content_type starts with 'archive/')"},
			{"is_binary", "bool", "true if compiled binary (ELF, Mach-O, PE — content_type starts with 'binary/')"},
			{"is_email", "bool", "true if email message or mbox archive (.eml, .mbox — content_type starts with 'email/')"},
			{"is_source", "bool", "true if source code (Go, Python, JS/TS, Rust, C/C++, Java, Ruby, Swift, Kotlin, Scala, Shell, Lua, Elixir, Clojure, Haskell, OCaml, Zig — content_type starts with 'source/')"},
			{"is_notebook", "bool", "true if computational notebook (Jupyter .ipynb or Zeppelin .zpln — content_type starts with 'notebook/')"},
			{"is_yaml", "bool", "true if YAML file (.yaml, .yml — covers CI configs, K8s manifests, GoReleaser, Docker Compose)"},
			{"is_toml", "bool", "true if TOML file (.toml — covers pyproject.toml, Cargo.toml, etc.). Also fires for Cargo.toml/Cargo.lock alongside is_cargo_manifest"},
			{"is_dockerfile", "bool", "true if Dockerfile or Containerfile"},
			{"is_makefile", "bool", "true if Makefile / GNUmakefile / BSDmakefile / makefile"},
			{"is_justfile", "bool", "true if Justfile / justfile (casey/just task runner)"},
			{"is_rakefile", "bool", "true if Rakefile (Ruby build script)"},
			{"is_license", "bool", "true if LICENSE / LICENCE / COPYING file (bare; extensioned variants like LICENSE.md still detect as markdown)"},
			{"is_changelog", "bool", "true if CHANGELOG / HISTORY file (bare; CHANGELOG.md detects as markdown)"},
			{"is_contributing", "bool", "true if CONTRIBUTING file (bare; CONTRIBUTING.md detects as markdown)"},
			{"is_codeowners", "bool", "true if CODEOWNERS / OWNERS file (GitHub, GitLab, Gerrit)"},
			{"is_gitignore", "bool", "true if .gitignore or .gitattributes"},
			{"is_dockerignore", "bool", "true if .dockerignore"},
			{"is_gomod", "bool", "true if go.mod or go.sum"},
			{"is_node_manifest", "bool", "true if package.json or package-lock.json (Node.js ecosystem; takes precedence over generic JSON detection)"},
			{"is_cargo_manifest", "bool", "true if Cargo.toml or Cargo.lock (Rust)"},
			{"is_pipfile", "bool", "true if Pipfile or Pipfile.lock (Python Pipenv)"},
			{"is_python_reqs", "bool", "true if requirements.txt (Python pip)"},
			{"is_gemfile", "bool", "true if Gemfile or Gemfile.lock (Ruby Bundler)"},
			{"is_procfile", "bool", "true if Procfile (Heroku/Foreman/PaaS process declaration)"},
			{"is_vagrantfile", "bool", "true if Vagrantfile (HashiCorp Vagrant VM dev environment)"},
			{"is_build", "bool", "true if build automation file — content_type starts with 'build/' (Dockerfile, Makefile, Justfile, Rakefile)"},
			{"is_repo_meta", "bool", "true if repo metadata — content_type starts with 'repo/' (LICENSE, CHANGELOG, CONTRIBUTING, CODEOWNERS)"},
			{"is_ignore", "bool", "true if ignore-pattern file — content_type starts with 'ignore/' (.gitignore, .gitattributes, .dockerignore)"},
			{"is_manifest", "bool", "true if dependency manifest — content_type starts with 'manifest/' (go.mod, package.json, Cargo.toml, Pipfile, requirements.txt, Gemfile)"},
			{"is_platform", "bool", "true if PaaS/VM platform config — content_type starts with 'platform/' (Procfile, Vagrantfile)"},
			{"is_ds_store", "bool", "true if `.DS_Store` (macOS Finder window-state file)"},
			{"is_localized", "bool", "true if `.localized` (macOS Finder localization marker — typically an empty file)"},
			{"is_thumbs_db", "bool", "true if `Thumbs.db` / `ehthumbs.db` / `ehthumbs_vista.db` (Windows thumbnail cache)"},
			{"is_desktop_ini", "bool", "true if `Desktop.ini` (Windows folder-customisation file)"},
			{"is_kde_directory", "bool", "true if `.directory` (KDE Dolphin folder-properties file)"},
			{"is_macos_metadata", "bool", "true if OS-generated macOS metadata — content_type starts with 'system/macos-' (.DS_Store, .localized)"},
			{"is_windows_metadata", "bool", "true if OS-generated Windows metadata — content_type starts with 'system/windows-' (Thumbs.db, Desktop.ini)"},
			{"is_linux_metadata", "bool", "true if OS-generated Linux metadata — content_type starts with 'system/linux-' (.directory)"},
			{"is_system_metadata", "bool", "true if any OS-generated metadata file — content_type starts with 'system/' (cross-OS family covering macOS / Windows / Linux)"},
			{"is_dmg", "bool", "true if Apple Disk Image (.dmg, UDIF format)"},
			{"is_iso", "bool", "true if ISO 9660 CD/DVD image (.iso)"},
			{"is_vhd", "bool", "true if Microsoft Virtual Hard Disk (.vhd, Connectix/Hyper-V legacy format)"},
			{"is_vhdx", "bool", "true if Microsoft Virtual Hard Disk v2 (.vhdx, Hyper-V modern format)"},
			{"is_vmdk", "bool", "true if VMware Virtual Machine Disk (.vmdk sparse-extent form — descriptor-only text .vmdk files detect as plain text)"},
			{"is_qcow2", "bool", "true if QEMU Copy-On-Write v2/v3 disk image (.qcow2, .qcow)"},
			{"is_wim", "bool", "true if Windows Imaging Format archive (.wim)"},
			{"is_disk_image", "bool", "true if any disk-image content type — content_type starts with 'disk-image/' (DMG, ISO, VHD, VHDX, VMDK, QCOW2, WIM)"},
			{"is_pkg", "bool", "true if macOS installer package (.pkg, XAR format)"},
			{"is_deb", "bool", "true if Debian binary package (.deb, ar archive format)"},
			{"is_rpm", "bool", "true if Red Hat Package Manager package (.rpm)"},
			{"is_appimage", "bool", "true if Linux AppImage (.appimage / .AppImage; ELF + appended SquashFS)"},
			{"is_install_package", "bool", "true if any install package — content_type starts with 'install/' (PKG, DEB, RPM, AppImage)"},
			{"is_test_file", "bool", "true if the source file's basename matches a test convention for its language (e.g. *_test.go for Go, test_*.py / *_test.py for Python, *.test.{js,ts,tsx} / *.spec.{js,ts,tsx} for JS/TS, *Test.java / *Tests.java for Java, *_spec.rb / *_test.rb for Ruby, *Tests.swift for Swift, *Test.kt / *Spec.scala for Kotlin/Scala). Only populated for source/* content types."},
			{"is_symlink", "bool", "true when the entry is a symbolic link (decided by os.Lstat — filesystem semantics, not 'shortcut' detection). Per-file attribute populated by the walker; matches the symlink itself, not its target."},
			{"is_broken_symlink", "bool", "true when is_symlink is true AND the target can't be resolved (dangling link). Other file-level attributes (size, mod_time, content_type) fall back to the symlink's own Lstat result rather than the absent target."},
			{"is_class", "bool", "true if JVM bytecode (.class file with `0xCAFEBABE` magic)"},
			{"is_pyc", "bool", "true if Python compiled bytecode (.pyc / .pyo)"},
			{"is_wasm", "bool", "true if WebAssembly module (.wasm with `\\0asm` magic)"},
			{"is_bytecode", "bool", "true if any VM bytecode — content_type starts with 'bytecode/' (JVM class, Python pyc, WebAssembly)"},
			{"is_fits", "bool", "true if FITS (Flexible Image Transport System) — the dominant astronomical data format used by every major observatory and space telescope (HST, JWST, Chandra, ALMA, Gaia, TESS, Kepler). Detected by `.fits` / `.fit` / `.fts` extension OR by the deterministic `SIMPLE  =` magic prefix at offset 0."},
			{"is_science_data", "bool", "true if any scientific-data format — content_type starts with 'science/'. Umbrella predicate; today fires only for FITS, positioned to extend over future VOTable / HDF5 / PDS / CDF additions."},
			{"md5", "string", "MD5 hex digest of the file's content (32 lowercase hex chars). Empty unless the caller opts in via --with-hashes / compute_hashes — hashing is not free. NSRL / VirusTotal / threat-intel-feed interop primary; consumed by hash-allowlist / hash-denylist matching when those flags are set. Cached alongside SHA1 + SHA256 in the index; single io.MultiWriter pass over the file so all three populate together."},
			{"sha1", "string", "SHA-1 hex digest of the file's content (40 lowercase hex chars). Same lifecycle as md5 — populated when --with-hashes / compute_hashes is set. NSRL ships MD5 + SHA1 as the canonical allowlist key; many forensic tools index by SHA1."},
			{"sha256", "string", "SHA-256 hex digest of the file's content (64 lowercase hex chars). Modern default; populated when --with-hashes / compute_hashes is set OR as a side effect of find_duplicates / find_near_duplicates. Stable across the file's (size, mtime) lifetime so the cached value survives any repeat walk."},
			{"created_at", "timestamp", "filesystem birth time of the file (when the inode was first created on the current filesystem). Populated for every file on modern filesystems (ext4 / APFS / NTFS / btrfs / xfs) via the same os.Stat call that reports size + mod_time — no extra I/O. Zero on filesystems / OSes that don't track it (rare). Use for forensic timeline reconstruction and (paired with mod_time) the is_btime_anomaly indicator. Distinct from disk_image_created_at, which is the timestamp embedded INSIDE a VHD / ISO file's own header."},
			{"metadata_changed_at", "timestamp", "filesystem ctime (last time the inode's metadata changed — permissions, ownership, hard-link count). Critical for tamper detection: an attacker chmod-ing a backdoor leaves no mod_time trace but does update ctime. Surfaced alongside created_at via the same syscall; zero when the OS doesn't expose ctime separately (Windows reports creation-time only)."},
			{"is_btime_anomaly", "bool", "fires when `created_at > mod_time` AND both are populated — the classic 'this file was placed here AFTER being modified elsewhere' indicator. Common causes: file restored from backup, copied between volumes (mod_time preserved, btime set to copy time), planted artefact, mount-time anomaly. False on normal files where the inode was created before any modifications."},
			{"magic_content_type", "string", "the content type detected from the file's first 512 bytes alone, ignoring extension. Populated only when the caller opts in via --check-disguised / check_disguised. Empty when no magic prefix matched OR when CheckDisguised wasn't set. Compare with extension_content_type to spot disguised files."},
			{"extension_content_type", "string", "the content type implied by the file's name (exact basename, then extension). Populated alongside magic_content_type when --check-disguised is set. Empty when no name-based match (extensionless files with unrecognised content)."},
			{"is_disguised", "bool", "fires when magic_content_type and extension_content_type are BOTH non-empty AND they disagree — the classic 'this .txt file contains a PE binary' / 'this .pdf is actually JavaScript' indicator. Requires --check-disguised. NB: legitimate name-vs-magic divergences (e.g. package.json matching manifest/node by name and json by magic) ALSO fire — pair with type predicates like `is_disguised && is_binary` for forensic-grade filtering."},
			{"is_known_good", "bool", "fires when the file's MD5 OR SHA1 OR SHA256 appears in the loaded hash allowlist (--hash-allowlist / hash_allowlist_path). Requires --with-hashes so the file's hashes are computed. The headline forensic-triage primitive: `!is_known_good` cuts an NSRL-allowlisted disk image's review surface by 80-95%."},
			{"is_known_bad", "bool", "fires when the file's MD5 OR SHA1 OR SHA256 appears in the loaded hash denylist (--hash-denylist / hash_denylist_path). Requires --with-hashes. Use with threat-intel feeds (IOC drops, internal known-malware lists) for first-pass triage."},
			{"similarity", "double", "cosine similarity (-1 to 1, typically 0 to 1 for embedding models) between this file's body embedding and the search call's query embedding. Populated when --semantic-query (CLI) / SemanticQuery (MCP) is set AND an Ollama embedding model is configured. 0 when no semantic query is set OR when the content type isn't text-shaped. Compose with type predicates and other filters: 'is_pdf && similarity > 0.7' / '!is_known_good && similarity > 0.5'."},
		},
		TypeSpecific: []AttributeDoc{
			{"title", "string", "title (front-matter, markdown h1, HTML title, PDF title, EPUB, office, audio)"},
			{"body", "string", "full file body (text content types only — markdown/text/html/csv/json/xml/source). Populated when --body (CLI) or include_body (MCP) is set; capped at body_max_bytes (default 1 MiB). Combine with CEL string methods: body.contains(\"X\"), body.matches(\"...\"), body.startsWith(\"Once upon\")."},
			{"word_count", "int", "word count (markdown body, plain text)"},
			{"line_count", "int", "line count (plain text)"},
			{"column_count", "int", "column count from header line (CSV/TSV)"},
			{"csv_columns", "list<str>", "header field names from the first CSV/TSV line"},
			{"page_count", "int", "page count (PDF)"},
			{"author", "string", "author (markdown front-matter, PDF, EPUB, office)"},
			{"language", "string", "locale code (EPUB, HTML <html lang>, markdown front-matter, PDF /Lang or XMP, office) OR programming-language name for source files (`go`, `python`, `javascript`, `typescript`, `rust`, `c`, `cpp`, `java`, `ruby`, `swift`, `kotlin`, `shell`, `lua`, `elixir`, `clojure`, `haskell`, `ocaml`, `zig`). Locale codes are 2-letter ISO 639-1; programming names are word tokens — they don't overlap."},
			{"root_element", "string", "root element name (XML)"},
			{"json_kind", "string", "'object' or 'array' (JSON)"},
			{"yaml_kind", "string", "'object' (mapping), 'array' (sequence), or 'scalar' — kind of the first YAML document's root node"},
			{"yaml_document_count", "int", "number of `---`-separated YAML documents in the file (1 for single-doc; >1 for K8s manifest bundles, etc.)"},
			{"module", "string", "Go module path declared in go.mod's `module` directive"},
			{"go_version", "string", "Go toolchain version declared in go.mod's `go` directive (e.g. '1.26.2')"},
			{"base_image", "string", "first `FROM <image>` directive in a Dockerfile / Containerfile"},
			{"project_types", "list<str>", "names of every project type the containing project matches (e.g. ['go', 'docker-compose']). Empty unless --resolve-projects (CLI) / resolve_projects=true (MCP) is set."},
			{"project_type", "string", "the first (alphabetically-sorted) match from project_types — convenience for `project_type == \"go\"` queries. Empty unless --resolve-projects is set."},
			{"is_static_site", "bool", "true when the file's resolved project type is a recognised static-site generator (`hugo`, `jekyll`, `eleventy`, `astro`, `gatsby`, `mkdocs`, `docusaurus`, `pelican`). Requires --resolve-projects."},
			{"img_width", "int", "image width in pixels"},
			{"img_height", "int", "image height in pixels"},
			{"camera_make", "string", "EXIF camera make (JPEG/TIFF/HEIC/PNG)"},
			{"camera_model", "string", "EXIF camera model"},
			{"lens", "string", "EXIF lens model"},
			{"taken_at", "timestamp", "EXIF DateTimeOriginal — image capture time"},
			{"orientation", "int", "EXIF orientation tag (1-8)"},
			{"gps_lat", "double", "GPS latitude in decimal degrees (north positive)"},
			{"gps_lon", "double", "GPS longitude in decimal degrees (east positive)"},
			{"iso", "int", "EXIF ISO sensitivity"},
			{"focal_length", "double", "EXIF focal length in mm"},
			{"f_stop", "double", "EXIF F-number (aperture)"},
			{"exposure_time", "double", "EXIF exposure time in seconds"},
			{"artist", "string", "audio artist tag (ID3v2 TPE1 / Vorbis ARTIST / iTunes ©ART)"},
			{"album", "string", "audio album tag"},
			{"album_artist", "string", "audio album-artist tag (compilations)"},
			{"composer", "string", "audio composer tag"},
			{"year", "int", "audio release year"},
			{"track", "int", "audio track number"},
			{"genre", "string", "audio genre tag"},
			{"duration", "double", "audio duration in seconds (FLAC STREAMINFO / MP3 Xing / OGG granule / MP4 mvhd)"},
			{"bitrate", "int", "average bitrate in kbps (computed file_size * 8 / duration / 1000) — applies to audio and video"},
			{"nominal_bitrate", "int", "codec/container-stored bitrate in kbps, distinct from the computed average. Audio: MP3 first-frame bitrate, OGG Vorbis bitrate_nominal, M4A esds avgBitrate (with maxBitrate fallback). Video: MP4 btrt avgBitrate, MKV/WebM TrackEntry Bitrate, AVI avih maxBytesPerSec. FLAC max_frame_size is not surfaced — it doesn't translate cleanly to kbps without frame timing."},
			{"color_primaries", "string", "video colour primaries — 'bt709' (HD), 'bt2020' (HDR / wide-gamut), 'p3' (DCI-P3 / Display P3), or '' if unspecified. Decoded from MP4 colr nclx or MKV Colour element."},
			{"color_transfer", "string", "video transfer characteristics — 'bt709' (SDR), 'pq' (SMPTE ST 2084 — HDR10), 'hlg' (Hybrid Log-Gamma — broadcast HDR), or '' if unspecified."},
			{"is_hdr", "bool", "true when transfer is PQ (HDR10 / HDR10+ / Dolby Vision base layer) or HLG. The canonical 'this video is HDR' signal."},
			{"subtitles", "bool", "true when at least one subtitle / closed-caption track is present (MP4 text/subt/sbtl/clcp tracks; MKV TrackType 17). Empty for AVI."},
			{"subtitle_languages", "list<str>", "ISO 639-2 language codes from each subtitle track in declaration order. Empty string when language is unspecified or marked 'und'."},
			{"replaygain_track_gain", "double", "ReplayGain track gain in dB (negative = quieter, positive = louder). Sourced from Vorbis comments (FLAC + OGG REPLAYGAIN_TRACK_GAIN), ID3v2 TXXX user-defined-text frames (MP3), and M4A iTunes ---- atoms (com.apple.iTunes namespace)."},
			{"replaygain_album_gain", "double", "ReplayGain album gain in dB. Same sources / coverage as replaygain_track_gain — Vorbis comments, ID3v2 TXXX, and M4A iTunes ---- atoms."},
			{"entry_count", "int", "archive entry count — number of files / directories inside a ZIP, TAR, or TAR.GZ. Always 1 for standalone .gz (gzip carries one stream per RFC 1952)."},
			{"uncompressed_size", "int", "archive total uncompressed size in bytes — sum of per-entry sizes for ZIP / TAR / TAR.GZ. For standalone .gz reads the 4-byte ISIZE footer; this is mod 2^32 so files whose payload exceeds 4 GiB report a wrapped value (matches `gzip -l`)."},
			{"top_level_entries", "list<str>", "archive root-level entry names, sorted and deduplicated. A traditional 'tarball-with-one-root-dir' has a single element; a sprawling archive that explodes into the working directory has many."},
			{"has_root_dir", "bool", "true when the archive has a single top-level entry — the Unix convention. Useful for spotting ZIP-bombs (false → many top-level entries that would all extract into the cwd)."},
			{"architectures", "list<str>", "compiled-binary CPU architectures (canonical names: x86_64, arm64, i386, arm, ppc64, riscv64, …). Length 1 for thin ELF / Mach-O / PE; length ≥ 2 for fat (universal) Mach-O."},
			{"bitness", "int", "compiled-binary bitness — 32 or 64. For fat Mach-O, reflects the first slice."},
			{"binary_format", "string", "compiled-binary format: 'elf', 'mach-o', or 'pe'. Mirrors the content-type subtype lifted to a CEL string."},
			{"binary_type", "string", "compiled-binary kind: 'executable', 'shared_library', 'object', 'core', or 'unknown'. Cross-format normalisation of ELF e_type, Mach-O Type, and PE Characteristics."},
			{"is_dynamically_linked", "bool", "true when the binary depends on shared libraries. ELF: PT_INTERP or PT_DYNAMIC present. Mach-O: any LC_LOAD_DYLIB load command. PE: non-empty import directory."},
			{"is_stripped", "bool", "true when the symbol table is absent or empty. ELF: Symbols() returns ErrNoSymbols. Mach-O: Symtab nil or empty. PE: IMAGE_FILE_DEBUG_STRIPPED bit set or empty COFF symbols."},
			{"entry_point", "int", "compiled-binary entry point — virtual address from ELF Entry / PE AddressOfEntryPoint. Zero for shared libraries, object files, and Mach-O (which reports entry-via-LC_MAIN offset that debug/macho doesn't expose)."},
			{"email_to", "list<str>", "RFC 5322 To header — addresses only (display names dropped to keep the list shape predictable for `\"alice@example.com\" in email_to` queries). For mbox archives, reflects the FIRST message."},
			{"email_cc", "list<str>", "RFC 5322 Cc header — addresses only. For mbox archives, reflects the FIRST message."},
			{"email_message_id", "string", "RFC 5322 Message-ID header (angle brackets stripped). For mbox archives, reflects the FIRST message."},
			{"email_in_reply_to", "string", "RFC 5322 In-Reply-To header (angle brackets stripped). For mbox archives, reflects the FIRST message."},
			{"sent_at", "timestamp", "email Date header parsed via mail.ParseDate. Mirrors taken_at for images. For mbox archives, reflects the FIRST message."},
			{"attachment_count", "int", "count of multipart parts that carry Content-Disposition: attachment or a filename parameter. Zero for non-multipart messages. Walks one level deep — nested multiparts are aggregated into their parent."},
			{"email_count", "int", "mbox archive — number of messages in the archive (count of `^From ` separator lines). Always 1 for single .eml files."},
			{"loc", "int", "source-code lines of code — non-blank, non-comment lines. Mixed lines (code with trailing `// comment`) count as code; lines that BEGIN with a comment marker count as comment. String literals containing `//` or `/*` are treated as code (no string-aware parsing)."},
			{"comment_loc", "int", "source-code comment lines — lines that begin with the language's line-comment marker, plus every line wholly inside a block comment. For OCaml (no line comments) only block-comment lines are counted."},
			{"blank_loc", "int", "source-code blank lines — empty or whitespace-only. A blank line inside a block comment counts as blank, matching the cloc / tokei convention."},
			{"cell_count", "int", "total number of cells/paragraphs in a notebook (Jupyter .ipynb / Zeppelin .zpln)"},
			{"code_cell_count", "int", "notebook code cells. For Jupyter: cells whose cell_type == \"code\". For Zeppelin: paragraphs whose editor language isn't markdown and whose text doesn't begin with %md."},
			{"markdown_cell_count", "int", "notebook markdown cells. For Jupyter: cells whose cell_type == \"markdown\". For Zeppelin: paragraphs whose editor language is markdown or whose text begins with %md."},
			{"kernel", "string", "notebook kernel/interpreter — Jupyter metadata.kernelspec.name (falling back to display_name); Zeppelin defaultInterpreterGroup."},
			{"sample_rate", "int", "audio sample rate in Hz"},
			{"channels", "int", "audio channel count (1 = mono, 2 = stereo, etc.)"},
			{"bit_depth", "int", "audio bits per sample (FLAC STREAMINFO / MP4 stsd sample_size; zero for MP3 / OGG which don't store it)"},
			{"video_codec", "string", "video codec (h264, h265, av1, vp9, vp8, mpeg4, etc.)"},
			{"audio_codec", "string", "audio codec for the audio track in a video container (aac, mp3, opus, vorbis, etc.)"},
			{"video_width", "int", "video frame width in pixels"},
			{"video_height", "int", "video frame height in pixels"},
			{"frame_rate", "double", "video frame rate in fps"},
			{"rotation", "int", "video display rotation in degrees (0 / 90 / 180 / 270) decoded from the MP4 tkhd matrix; 0 for non-rotated, non-MP4 formats, or non-pure-rotation matrices"},
			{"disk_image_format", "string", "disk-image format identifier — 'udif' (DMG), 'iso9660' (ISO), 'vhd-fixed' / 'vhd-dynamic' / 'vhd-differencing' (VHD), 'vhdx' (VHDX), 'vmdk-sparse' (VMDK), 'qcow2' (QCOW2), or 'wim' (WIM). Set whenever content_type starts with 'disk-image/'."},
			{"virtual_size", "int", "disk-image logical capacity in bytes — the size the image presents when mounted, not the compressed/sparse on-disk footprint. DMG: SectorCount × 512. ISO: volume_space_size × 2048. VHD: CurrentSize. VHDX: VirtualDiskSize metadata item (best-effort; 0 if region walk fails). VMDK: capacity × 512. QCOW2: header `size` field. WIM: 0 (file-level archive, not a disk — use the always-on `size` attribute for on-disk footprint)."},
			{"disk_type", "string", "disk-image sub-format. VHD: 'fixed' / 'dynamic' / 'differencing'. VMDK: 'sparse' / 'sparse-compressed'. Empty for DMG / ISO / VHDX / QCOW2 / WIM."},
			{"volume_label", "string", "ISO 9660 volume identifier from the primary volume descriptor (32 chars, trimmed)."},
			{"disk_image_created_at", "timestamp", "disk-image creation timestamp parsed from inside the file's own header. VHD: TimeStamp field (seconds since 2000-01-01 UTC). ISO: volume_creation_date_and_time from the PVD. Empty for other disk-image formats and non-disk-image files. (NOT the filesystem-level birth time — see `created_at` for that.)"},
			{"cluster_bits", "int", "QCOW2 cluster size as power of 2 (cluster size in bytes = 1 << cluster_bits). Typical values 16 (64 KiB) or 17 (128 KiB)."},
			{"is_encrypted", "bool", "QCOW2 encryption flag — true when crypt_method != 0 (1 = AES, 2 = LUKS). False (or absent) for unencrypted images and for other formats."},
			{"image_count", "int", "WIM archive image count — number of distinct system images contained in a WIM file."},
			{"package_format", "string", "install-package format identifier — 'xar' (macOS pkg), 'deb' (Debian), 'rpm' (Red Hat), 'appimage' (Linux portable). Set whenever content_type starts with 'install/'."},
			{"package_name", "string", "install-package name extracted from format-specific metadata. RPM: parsed from the Lead's <name>-<version>-<release> field. DEB and PKG don't carry the name in the file header — extracting it requires walking the inner control.tar.* or TOC respectively (out of scope for v1)."},
			{"package_version", "string", "install-package version. RPM: second-to-last `-`-delimited segment of the Lead name. Empty for DEB / PKG / AppImage in v1."},
			{"package_release", "string", "install-package release / build identifier. RPM: last `-`-delimited segment of the Lead name (often distro-specific, e.g. '1.el9'). Empty for other formats."},
			{"package_arch", "string", "install-package target architecture, canonical lowercase ('i386', 'x86_64', 'aarch64', 'ppc64le', 'riscv64', etc). RPM: decoded from the Lead's archnum field. Empty for other formats in v1."},
			{"package_kind", "string", "install-package classification. RPM: 'binary' or 'source'. PKG: 'macos-installer'. AppImage: 'linux-portable'. DEB: 'binary' (the only standard kind for .deb files)."},
			{"appimage_version", "int", "AppImage on-disk format version (1 or 2). v2 is the current format; v1 was superseded in 2017."},
			{"license_id", "string", "SPDX license identifier detected by scanning the body of a LICENSE / LICENCE / COPYING / UNLICENSE file. Recognised: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, GPL-3.0, GPL-2.0, LGPL-3.0, LGPL-2.1, AGPL-3.0, MPL-2.0, ISC, Unlicense, CC0-1.0, BSL-1.0. Empty when the file doesn't match a recognised license. .md license variants (e.g. LICENSE.md) currently detect as markdown and don't populate license_id — use is_markdown && name.startsWith(\"LICENSE\") as a fallback."},
			{"target_path", "string", "for symlinks, the raw link target as recorded on disk (relative or absolute — whatever the user passed to `ln -s`). Empty for non-symlinks. Surface alongside is_symlink and is_broken_symlink to audit dangling references, follow chains, or filter out symlinked duplicates."},
			{"bytecode_format", "string", "VM bytecode format identifier — 'jvm' (Java .class), 'python' (CPython .pyc / .pyo), 'wasm' (WebAssembly). Set whenever content_type starts with 'bytecode/'."},
			{"runtime_version", "string", "VM bytecode runtime version, human-readable. JVM: 'Java 8'..'Java 24' (mapped from the .class major version per JVMS §4.1). Python: 'Python 3.7'..'Python 3.14' (mapped from the .pyc magic number table). WASM: 'WebAssembly 1.0' (from the module's u32 version header)."},
			{"class_name", "string", "JVM .class — the fully-qualified class name (e.g. 'java/lang/String') resolved through CONSTANT_Class → CONSTANT_Utf8 in the constant pool."},
			{"super_class", "string", "JVM .class — the superclass's fully-qualified name. Usually 'java/lang/Object' for most application classes."},
			{"interfaces", "list<str>", "JVM .class — fully-qualified names of every interface the class implements (e.g. ['java/io/Serializable'])."},
			{"method_count", "int", "JVM .class — number of methods declared on the class (including synthetic / bridge methods generated by javac)."},
			{"field_count", "int", "JVM .class — number of fields declared on the class."},
			{"access_flags", "list<str>", "JVM .class — canonical names of the class-level access flags ('public', 'final', 'super', 'interface', 'abstract', 'synthetic', 'annotation', 'enum', 'module'). Same vocabulary the JVMS access_flags table defines."},
			{"python_version", "string", "Python .pyc — the bytecode's source Python release (e.g. '3.11'). Resolved from the 2-byte LE magic number per CPython's MAGIC_NUMBER table."},
			{"source_mtime", "timestamp", "Python .pyc — the source .py file's mtime that was current when the .pyc was compiled. Zero for hash-based .pyc files (PEP 552, Python 3.7+ when SOURCE_DATE_EPOCH or --check-hash-based-pycs is in play)."},
			{"wasm_version", "int", "WebAssembly module format version. Currently 1 is the only released version of the binary spec."},
			{"section_count", "int", "WebAssembly module section count — how many top-level sections (type, import, function, table, memory, global, export, start, element, code, data, datacount, custom) the module declares."},
			{"import_count", "int", "WebAssembly module — number of entries in the Import section. Useful for spotting modules with unusually large host-binding surfaces."},
			{"export_count", "int", "WebAssembly module — number of entries in the Export section. Zero for modules used as pure libraries (typically you'd expect 1+ for invocation surface)."},
			{"science_format", "string", "scientific-data format identifier — 'fits' (Flexible Image Transport System). Set whenever content_type starts with 'science/'."},
			{"telescope", "string", "FITS TELESCOP keyword — telescope or observatory name (e.g. 'HST', 'JWST', 'VLT', 'Gemini-North'). Pulled verbatim from the primary HDU."},
			{"instrument", "string", "FITS INSTRUME keyword — detector / instrument name (e.g. 'WFC3', 'NIRCam', 'STIS', 'X-shooter')."},
			{"object", "string", "FITS OBJECT keyword — observed target name (e.g. 'M31', 'NGC 1234', 'Vega'). Also lifted to the shared `title` attribute for cross-family vocabulary."},
			{"observer", "string", "FITS OBSERVER keyword — observer / PI name. Also lifted to the shared `author` attribute."},
			{"date_obs", "string", "FITS DATE-OBS keyword — raw observation date string from the header. Kept verbatim for exact-match filters; the parsed timestamp is exposed via the shared `taken_at` attribute (ISO 8601, falling back to `YYYY-MM-DD`)."},
			{"exptime", "double", "FITS EXPTIME keyword — exposure time in seconds."},
			{"filter", "string", "FITS FILTER keyword — bandpass / filter wheel position (e.g. 'F814W', 'g', 'Halpha')."},
			{"airmass", "double", "FITS AIRMASS keyword — atmospheric airmass at mid-exposure (1.0 = zenith; higher = closer to horizon)."},
			{"ra", "double", "FITS right ascension in degrees. Prefers CRVAL1 (WCS standard) and falls back to RA (older convention) when CRVAL1 is absent."},
			{"dec", "double", "FITS declination in degrees. Prefers CRVAL2 (WCS) over DEC."},
			{"bitpix", "int", "FITS BITPIX keyword — pixel data type. 8 / 16 / 32 / 64 = unsigned / signed integer of that width; -32 / -64 = IEEE float32 / float64 (negative values denote floating-point)."},
			{"naxis", "int", "FITS NAXIS keyword — dimensionality of the data array (0 = no data unit / metadata-only HDU; 1 = spectrum; 2 = image; 3 = cube / RGB; ≥4 = hypercube / IFU stack)."},
			{"naxis1", "int", "FITS NAXIS1 keyword — first-axis length (typically image width in pixels for 2D arrays)."},
			{"naxis2", "int", "FITS NAXIS2 keyword — second-axis length (typically image height for 2D arrays)."},
			{"hdu_count", "int", "FITS file — number of Header-Data Units (HDUs). 1 for single-HDU files; 2+ for multi-extension FITS (MEF) used by mosaic instruments and complex pipelines. Capped at 100 to defend against adversarial headers."},
			{"fits_kind", "string", "FITS primary HDU classification — 'image' (SIMPLE=T with NAXIS>0, or XTENSION=IMAGE), 'table' (XTENSION=TABLE), 'binary-table' (XTENSION=BINTABLE), 'primary' (metadata-only primary HDU with NAXIS=0)."},
		},
		Frontmatter: []AttributeDoc{
			{"frontmatter", "map", "full parsed front-matter, e.g. frontmatter.category"},
			{"frontmatter_format", "string", "'yaml', 'toml', 'json', or '' if none"},
			{"tags", "list<str>", "front-matter tags (single string is wrapped)"},
			{"categories", "list<str>", "front-matter categories"},
			{"draft", "bool", "front-matter draft flag"},
			{"date", "timestamp", "front-matter date"},
		},
		Functions: []FunctionDoc{
			{
				Name:        "levenshtein",
				Signature:   "levenshtein(string, string) -> int",
				Description: "Edit distance (rune-aware, case-sensitive). Counts insertions, deletions, and substitutions needed to turn the first string into the second.",
				Example:     `is_audio && levenshtein(artist, "Radiohead") <= 2`,
			},
			{
				Name:        "soundex",
				Signature:   "soundex(string) -> string",
				Description: "American Soundex phonetic code (4-character ASCII, e.g. 'Robert' -> 'R163'). Useful for matching name spellings that sound alike.",
				Example:     `is_image && soundex(camera_make) == soundex("Nikon")`,
			},
			{
				Name:        "ngrams",
				Signature:   "ngrams(string, int) -> list<string>",
				Description: "Character-level n-grams of the input (sliding window, length n). Empty list when n <= 0 or n exceeds the rune length of the string.",
				Example:     `ngrams("kubernetes", 3).size() > 5`,
			},
			{
				Name:        "ngram_similarity",
				Signature:   "ngram_similarity(string, string, int) -> double",
				Description: "Jaccard similarity over character n-gram sets, ranging 0.0 (no overlap) to 1.0 (identical sets). Both empty -> 1.0; only one empty -> 0.0.",
				Example:     `is_markdown && ngram_similarity(title, "kubernetes", 2) > 0.6`,
			},
			{
				Name:        "point_in_polygon",
				Signature:   "point_in_polygon(double, double, list<double>) -> bool",
				Description: "Test whether (lat, lon) lies inside an arbitrary polygon. The third argument is a flat list of alternating lat,lon pairs: [lat0, lon0, lat1, lon1, ...]. Polygon need not be explicitly closed; planar ray-casting (good for neighbourhoods / cities / small countries).",
				Example:     `is_image && point_in_polygon(gps_lat, gps_lon, [-34.10, 18.30, -34.10, 18.50, -33.90, 18.50, -33.90, 18.30])`,
			},
		},
	}
}
