package celexpr

// AttributeDoc describes a single CEL attribute available in expressions.
type AttributeDoc struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// FunctionDoc describes a CEL-callable function registered on the
// environment. Unlike attributes, functions have a signature (the formal
// argument list and return type), so the schema needs a richer doc type.
type FunctionDoc struct {
	Name        string `json:"name"`
	Signature   string `json:"signature"`
	Description string `json:"description"`
	Example     string `json:"example,omitempty"`
}

// SchemaDoc groups the documented CEL attributes by category, plus the
// callable built-in functions registered on the environment.
type SchemaDoc struct {
	Common       []AttributeDoc `json:"common"`
	TypeSpecific []AttributeDoc `json:"type_specific"`
	Frontmatter  []AttributeDoc `json:"frontmatter"`
	Functions    []FunctionDoc  `json:"functions"`
}

// Schema returns the structured documentation for every CEL attribute
// and function the evaluator declares. Both the CLI's --list output and
// the MCP list_attributes tool format their output from this.
func Schema() SchemaDoc {
	return SchemaDoc{
		Common: []AttributeDoc{
			{"name", "string", "filename"},
			{"path", "string", "full path"},
			{"dir", "string", "parent directory"},
			{"size", "int", "file size in bytes"},
			{"ext", "string", "file extension (e.g. '.md')"},
			{"content_type", "string", "detected content type"},
			{"mod_time", "timestamp", "file last-modified time (filesystem mtime as reported by os.Stat). Always populated for real files. Useful for time-relative filtering: `mod_time > timestamp(\"2025-01-01T00:00:00Z\")` or `mod_time < timestamp(\"...\")`. Same value the `--sort mod_time` key uses."},
			{"is_markdown", "bool", "true if markdown file"},
			{"is_json", "bool", "true if JSON file (.json + package.json/package-lock.json which also fire is_node_manifest)"},
			{"is_xml", "bool", "true if XML file"},
			{"is_html", "bool", "true if HTML file"},
			{"is_pdf", "bool", "true if PDF file"},
			{"is_image", "bool", "true if image file"},
			{"is_text", "bool", "true if plain-text file (.txt, .text, .log) — also fires for requirements.txt, LICENSE, CHANGELOG, CONTRIBUTING which are plain text by convention"},
			{"is_csv", "bool", "true if CSV/TSV file"},
			{"is_epub", "bool", "true if EPUB book"},
			{"is_office", "bool", "true if office document (DOCX, XLSX, PPTX, ODT — content_type starts with 'office/')"},
			{"is_audio", "bool", "true if audio file (MP3, M4A, FLAC, OGG — content_type starts with 'audio/')"},
			{"is_video", "bool", "true if video file (MP4, MOV, MKV, WebM, AVI — content_type starts with 'video/')"},
			{"is_archive", "bool", "true if archive file (ZIP, TAR, TAR.GZ, GZIP — content_type starts with 'archive/')"},
			{"is_binary", "bool", "true if compiled binary (ELF, Mach-O, PE — content_type starts with 'binary/')"},
			{"is_email", "bool", "true if email message or mbox archive (.eml, .mbox — content_type starts with 'email/')"},
			{"is_source", "bool", "true if source code (Go, Python, JS/TS, Rust, C/C++, Java, Ruby, Swift, Kotlin, Scala, Shell, Lua, Elixir, Clojure, Haskell, OCaml, Zig — content_type starts with 'source/')"},
			{"is_notebook", "bool", "true if computational notebook (Jupyter .ipynb or Zeppelin .zpln — content_type starts with 'notebook/')"},
			{"is_yaml", "bool", "true if YAML file (.yaml, .yml — covers CI configs, K8s manifests, GoReleaser, Docker Compose)"},
			{"is_toml", "bool", "true if TOML file (.toml — covers pyproject.toml, Cargo.toml, etc.). Also fires for Cargo.toml/Cargo.lock alongside is_cargo_manifest"},
			{"is_dockerfile", "bool", "true if Dockerfile or Containerfile"},
			{"is_makefile", "bool", "true if Makefile / GNUmakefile / BSDmakefile / makefile"},
			{"is_justfile", "bool", "true if Justfile / justfile (casey/just task runner)"},
			{"is_rakefile", "bool", "true if Rakefile (Ruby build script)"},
			{"is_license", "bool", "true if LICENSE / LICENCE / COPYING file (bare; extensioned variants like LICENSE.md still detect as markdown)"},
			{"is_changelog", "bool", "true if CHANGELOG / HISTORY file (bare; CHANGELOG.md detects as markdown)"},
			{"is_contributing", "bool", "true if CONTRIBUTING file (bare; CONTRIBUTING.md detects as markdown)"},
			{"is_codeowners", "bool", "true if CODEOWNERS / OWNERS file (GitHub, GitLab, Gerrit)"},
			{"is_gitignore", "bool", "true if .gitignore or .gitattributes"},
			{"is_dockerignore", "bool", "true if .dockerignore"},
			{"is_gomod", "bool", "true if go.mod or go.sum"},
			{"is_node_manifest", "bool", "true if package.json or package-lock.json (Node.js ecosystem; takes precedence over generic JSON detection)"},
			{"is_cargo_manifest", "bool", "true if Cargo.toml or Cargo.lock (Rust)"},
			{"is_pipfile", "bool", "true if Pipfile or Pipfile.lock (Python Pipenv)"},
			{"is_python_reqs", "bool", "true if requirements.txt (Python pip)"},
			{"is_gemfile", "bool", "true if Gemfile or Gemfile.lock (Ruby Bundler)"},
			{"is_procfile", "bool", "true if Procfile (Heroku/Foreman/PaaS process declaration)"},
			{"is_vagrantfile", "bool", "true if Vagrantfile (HashiCorp Vagrant VM dev environment)"},
			{"is_build", "bool", "true if build automation file — content_type starts with 'build/' (Dockerfile, Makefile, Justfile, Rakefile)"},
			{"is_repo_meta", "bool", "true if repo metadata — content_type starts with 'repo/' (LICENSE, CHANGELOG, CONTRIBUTING, CODEOWNERS)"},
			{"is_ignore", "bool", "true if ignore-pattern file — content_type starts with 'ignore/' (.gitignore, .gitattributes, .dockerignore)"},
			{"is_manifest", "bool", "true if dependency manifest — content_type starts with 'manifest/' (go.mod, package.json, Cargo.toml, Pipfile, requirements.txt, Gemfile)"},
			{"is_platform", "bool", "true if PaaS/VM platform config — content_type starts with 'platform/' (Procfile, Vagrantfile)"},
			{"is_ds_store", "bool", "true if `.DS_Store` (macOS Finder window-state file)"},
			{"is_localized", "bool", "true if `.localized` (macOS Finder localization marker — typically an empty file)"},
			{"is_thumbs_db", "bool", "true if `Thumbs.db` / `ehthumbs.db` / `ehthumbs_vista.db` (Windows thumbnail cache)"},
			{"is_desktop_ini", "bool", "true if `Desktop.ini` (Windows folder-customisation file)"},
			{"is_kde_directory", "bool", "true if `.directory` (KDE Dolphin folder-properties file)"},
			{"is_plist", "bool", "true if Apple property-list file (.plist) — both binary (`bplist00` magic) and XML variants. Surfaces bundle identity, executable path, min-OS version, plus LaunchAgent / LaunchDaemon persistence keys. Always fires `is_macos_metadata` even without the `system/macos-` prefix because plist is Apple-specific by overwhelming convention."},
			{"is_macos_metadata", "bool", "true if OS-generated macOS metadata — content_type starts with 'system/macos-' (.DS_Store, .localized) OR equals 'system/plist' (the plist content type is named without the macos- prefix but is Apple-specific by convention)"},
			{"is_windows_metadata", "bool", "true if OS-generated Windows metadata — content_type starts with 'system/windows-' (Thumbs.db, Desktop.ini)"},
			{"is_linux_metadata", "bool", "true if OS-generated Linux metadata — content_type starts with 'system/linux-' (.directory)"},
			{"is_system_metadata", "bool", "true if any OS-generated metadata file — content_type starts with 'system/' (cross-OS family covering macOS / Windows / Linux)"},
			{"is_dmg", "bool", "true if Apple Disk Image (.dmg, UDIF format)"},
			{"is_iso", "bool", "true if ISO 9660 CD/DVD image (.iso)"},
			{"is_vhd", "bool", "true if Microsoft Virtual Hard Disk (.vhd, Connectix/Hyper-V legacy format)"},
			{"is_vhdx", "bool", "true if Microsoft Virtual Hard Disk v2 (.vhdx, Hyper-V modern format)"},
			{"is_vmdk", "bool", "true if VMware Virtual Machine Disk (.vmdk sparse-extent form — descriptor-only text .vmdk files detect as plain text)"},
			{"is_qcow2", "bool", "true if QEMU Copy-On-Write v2/v3 disk image (.qcow2, .qcow)"},
			{"is_wim", "bool", "true if Windows Imaging Format archive (.wim)"},
			{"is_disk_image", "bool", "true if any disk-image content type — content_type starts with 'disk-image/' (DMG, ISO, VHD, VHDX, VMDK, QCOW2, WIM)"},
			{"is_pkg", "bool", "true if macOS installer package (.pkg, XAR format)"},
			{"is_deb", "bool", "true if Debian binary package (.deb, ar archive format)"},
			{"is_rpm", "bool", "true if Red Hat Package Manager package (.rpm)"},
			{"is_appimage", "bool", "true if Linux AppImage (.appimage / .AppImage; ELF + appended SquashFS)"},
			{"is_install_package", "bool", "true if any install package — content_type starts with 'install/' (PKG, DEB, RPM, AppImage)"},
			{"is_test_file", "bool", "true if the source file's basename matches a test convention for its language (e.g. *_test.go for Go, test_*.py / *_test.py for Python, *.test.{js,ts,tsx} / *.spec.{js,ts,tsx} for JS/TS, *Test.java / *Tests.java for Java, *_spec.rb / *_test.rb for Ruby, *Tests.swift for Swift, *Test.kt / *Spec.scala for Kotlin/Scala). Only populated for source/* content types."},
			{"is_generated_code", "bool", "true when the source file's first ~20 lines contain a recognised codegen marker — Go's `// Code generated ... DO NOT EDIT.`, Python's `# Generated by`, C#'s `// <auto-generated>`, the cross-language `@generated` annotation, plus the ecosystem's universal `// DO NOT EDIT` / `// Generated by` prefixes (Java / Kotlin / Scala / Rust / JS / TS / Ruby / Swift / PHP / Perl / shell). Filter out generated artefacts from code-review queries: `is_source && !is_generated_code && !is_test_file` is the 'production code only' filter. Issue #276."},
			{"is_symlink", "bool", "true when the entry is a symbolic link (decided by os.Lstat — filesystem semantics, not 'shortcut' detection). Per-file attribute populated by the walker; matches the symlink itself, not its target."},
			{"is_broken_symlink", "bool", "true when is_symlink is true AND the target can't be resolved (dangling link). Other file-level attributes (size, mod_time, content_type) fall back to the symlink's own Lstat result rather than the absent target."},
			{"is_class", "bool", "true if JVM bytecode (.class file with `0xCAFEBABE` magic)"},
			{"is_pyc", "bool", "true if Python compiled bytecode (.pyc / .pyo)"},
			{"is_wasm", "bool", "true if WebAssembly module (.wasm with `\\0asm` magic)"},
			{"is_bytecode", "bool", "true if any VM bytecode — content_type starts with 'bytecode/' (JVM class, Python pyc, WebAssembly)"},
			{"is_fits", "bool", "true if FITS (Flexible Image Transport System) — the dominant astronomical data format used by every major observatory and space telescope (HST, JWST, Chandra, ALMA, Gaia, TESS, Kepler). Detected by `.fits` / `.fit` / `.fts` extension OR by the deterministic `SIMPLE  =` magic prefix at offset 0."},
			{"is_votable", "bool", "true if VOTable (IVOA tabular standard for astronomical catalogs and query results). Used by every VO service (Simbad, Vizier, MAST, Gaia archive). Detected by `.vot` / `.votable` extension. XML-named VOTable files detect as plain XML — rename to `.vot` to engage the VOTable parser."},
			{"is_hdf5", "bool", "true if HDF5 (Hierarchical Data Format v5). Used by LSST, LIGO, NetCDF4, every modern simulation pipeline, PyTorch and NumPy checkpoint formats. Detected by the 8-byte `\\x89HDF\\r\\n\\x1a\\n` magic prefix at offset 0 AND by `.h5` / `.hdf5` / `.hdf` / `.he5` extension. Superblocks placed at non-zero file offsets (the spec allows 512 / 1024 / ...) detect by extension only."},
			{"is_pds3", "bool", "true if NASA Planetary Data System v3 label (PVL format) — legacy archives for Voyager, Galileo, Cassini, MESSENGER, Mars rovers through Curiosity. Detected by `.lbl` extension AND by the `PDS_VERSION_ID` magic prefix at offset 0. Use is_pds3 vs is_pds4 to discriminate variants; is_pds umbrella fires for both."},
			{"is_pds4", "bool", "true if NASA Planetary Data System v4 label (XML format) — current standard for Perseverance, Lucy, OSIRIS-REx and future missions. Detected by `.lblx` extension. v1 supports `Product_Observational` only — other product kinds (Bundle / Collection / Document) detect but don't populate attributes. XML-named PDS4 labels detect as plain XML (limitation; rename to `.lblx` to engage)."},
			{"is_pds", "bool", "true if PDS3 OR PDS4 — umbrella predicate over both NASA Planetary Data System variants. Compose with is_pds3 / is_pds4 to scope to a specific format era."},
			{"is_cdf", "bool", "true if NASA Common Data Format v3+ (heliophysics / space-physics time-series). Used by ACE, Wind, Cluster, MMS, Parker Solar Probe, Solar Orbiter. Detected by the 4-byte `0xCDF30001` magic prefix at offset 0 plus the `.cdf` extension. v2.x files are not supported."},
			{"is_science_data", "bool", "true if any scientific-data format — content_type starts with 'science/'. Umbrella predicate covering FITS, VOTable, HDF5, PDS (3+4), and CDF."},
			{"is_sqlite", "bool", "true if SQLite v3 database file. Detected by the 16-byte `SQLite format 3\\0` magic prefix at offset 0 plus the `.db` / `.sqlite` / `.sqlite3` / `.db3` extensions. SQLCipher / encrypted databases don't expose the magic (it's encrypted along with the rest of the file) and detect as binary noise. Deliberately does NOT fire for WAL / SHM sidecars — use `is_sqlite_wal` / `is_sqlite_shm` for those."},
			{"is_sqlite_wal", "bool", "true if SQLite write-ahead log (WAL) sidecar. Detected by the 4-byte magic `0x377F0682` (big-endian checksums) or `0x377F0683` (little-endian checksums) at offset 0 plus the `.db-wal` / `.sqlite-wal` / `.sqlite3-wal` extensions. WAL files sit next to a parent SQLite database in WAL mode (`sqlite_format_version == 2`) and hold pages committed but not yet checkpointed. Does NOT imply `is_sqlite` / `is_database` — compose with OR when needed."},
			{"is_sqlite_shm", "bool", "true if SQLite shared-memory (SHM) sidecar — the mmap'd index used by multiple connections to coordinate WAL access. Extension-only detection (`.db-shm` / `.sqlite-shm` / `.sqlite3-shm`); the on-disk format is implementation-defined. Mere presence indicates the parent DB is in WAL mode AND has had at least one active connection. Does NOT imply `is_sqlite` / `is_database`."},
			{"is_database", "bool", "true if any database file — content_type starts with 'database/'. Umbrella predicate; today fires for `database/sqlite` only, NOT for the `-wal` / `-shm` sidecars (they accompany a database, they aren't one). Positioned to extend over future DuckDB / PostgreSQL-dump / BoltDB additions."},
			{"is_bookmark_file", "bool", "true if any browser bookmark file — content_type starts with 'browser/bookmarks-'. Umbrella predicate covering Chromium-family (Chrome / Brave / Edge / Chromium / Opera) and Safari. Compose with `body.contains(...)` after `--body` to grep across saved-page URLs and titles in one query."},
			{"is_chromium_bookmarks", "bool", "true if Chromium-family bookmarks JSON — detected by exact basename `Bookmarks` (no extension) plus a `roots.bookmark_bar` content discriminator. Beats generic JSON detection via FilenameMatcher-exact precedence. Same file shape across Chrome / Chromium / Edge / Brave / Opera / Vivaldi / Arc."},
			{"is_safari_bookmarks", "bool", "true if Safari `Bookmarks.plist` — detected by exact basename plus a root-dict `WebBookmarkType` content discriminator. Beats generic plist detection via FilenameMatcher-exact precedence."},
			{"is_chat_export", "bool", "true if any chat-export archive — content_type starts with `chat/`. Umbrella over `is_slack_export` / `is_discord_export` / `is_signal_export`. All three are plain `.json` files detected by top-level JSON shape (a content discriminator), not extension. Compose with `body.contains(...)` after `--body` to grep message text across a workspace export."},
			{"is_slack_export", "bool", "true if a Slack workspace-export channel file — a top-level array of message objects (`ts` / `user` / `text`), or the wrapped `{\"messages\": [...]}` form. Channel + workspace names are derived from the `{workspace}/{channel}/YYYY-MM-DD.json` directory layout."},
			{"is_discord_export", "bool", "true if a DiscordChatExporter JSON dump — a top-level object carrying the `guild` + `channel` + `messages` triad. `chat_channel` = channel name, `chat_workspace` = guild name."},
			{"is_signal_export", "bool", "true if a signal-cli `--json` dump — newline-delimited (or array-wrapped) `envelope` objects. `chat_channel` is derived from the file basename (the contact); Signal has no workspace concept."},
			{"is_font", "bool", "true if any font file — content_type starts with `font/`. Umbrella over `is_ttf` / `is_otf` / `is_font_collection` / `is_woff` / `is_woff2`. The shared `font_family` attribute also dual-surfaces to the common `title` variable (cross-family vocabulary — `title.contains(\"Inter\")` fires on fonts as well as documents)."},
			{"is_ttf", "bool", "true if TrueType font (.ttf) — bare sfnt container with TrueType `glyf` outlines. Magic at offset 0 is `0x00010000` (the sfnt scaler version). Includes the legacy Apple `true` magic for old fonts."},
			{"is_otf", "bool", "true if OpenType font (.otf) — sfnt container with PostScript/CFF outlines. Magic at offset 0 is `OTTO`. `font_outline_kind` discriminates `cff` (legacy CFF) vs `cff2` (modern variable-font-friendly CFF2)."},
			{"is_font_collection", "bool", "true if TrueType / OpenType Collection (.ttc / .otc) — one file with N embedded sfnts, typically variations of the same family (e.g. `Helvetica.ttc` ships ~12 weight + style combinations on macOS). `font_collection_count` carries the member count; `font_collection_families` lists unique family names across all members."},
			{"is_woff", "bool", "true if Web Open Font Format v1 (.woff) — zlib-compressed sfnt wrapper. The `name` table is decompressed for attribute extraction; other tables stay in their compressed slots in v1."},
			{"is_woff2", "bool", "true if Web Open Font Format v2 (.woff2) — brotli-compressed sfnt with transformed table encoding. The metadata tables (`name` / `OS/2` / `head` / `post` / `maxp` / `fvar`) are sliced from the decompressed stream and parsed; transformed `glyf` / `loca` / `hmtx` tables are skipped (file-search-on doesn't surface glyph data). `font_family`, `font_weight`, `font_axes` etc. all populate on `.woff2` exactly as they do on `.ttf`."},
			{"is_variable_font", "bool", "true if the font has an `fvar` table — modern variable-font design space with one or more axes (`wght`, `wdth`, `slnt`, `ital`, `opsz`, …). `font_axis_count` carries the axis count; `font_axes` lists the axis tags."},
			{"is_color_font", "bool", "true if the font has any color outline table (`COLR` / `SVG ` / `sbix` / `CBDT`). Color emoji fonts (Apple Color Emoji, Noto Color Emoji, Segoe UI Emoji) and modern decorative typefaces with multi-colour glyphs fire this."},
			{"is_monospace_font", "bool", "true if `post.isFixedPitch` is non-zero — every glyph has the same advance width. Programming fonts (Menlo, Fira Code, JetBrains Mono, Cascadia Code) fire this. Distinct from the (variable-width) `proportional` default."},
			{"is_italic_font", "bool", "true if the font is italic, oblique, or slanted. Decoded from `head.macStyle` italic bit OR `post.italicAngle` ≠ 0 (Apple's two competing italic-detection conventions)."},
			{"is_bold_font", "bool", "true if `OS/2.usWeightClass` >= 700 (DemiBold / Bold / ExtraBold / Black) OR `head.macStyle` bold bit set. The weight-class threshold of 700 matches CSS's `font-weight: bold` convention."},
			{"is_raw_photo", "bool", "true if any camera RAW photo — content_type starts with `image/raw-`. Umbrella over `is_cr2` / `is_cr3` / `is_nef` / `is_arw` / `is_dng` / `is_raf` / `is_orf` / `is_rw2`. Also fires `is_image` via the shared `image/` prefix. Camera EXIF (`camera_make`, `camera_model`, `lens`, `taken_at`, GPS, ISO, focal_length, f_stop, exposure_time) populates via the same `imagemeta.Decode` path as JPEG / TIFF."},
			{"is_cr2", "bool", "true if Canon CR2 (.cr2) — TIFF-based RAW, primary Canon DSLR format pre-2018. Detection is extension-only (the shared TIFF magic stays with `image/tiff` to avoid ambiguous dispatch)."},
			{"is_cr3", "bool", "true if Canon CR3 (.cr3) — ISO BMFF / `crx ` brand container, Canon DSLR / mirrorless format from 2018 onwards. Detection is extension-only (the `ftyp` magic at offset 4 is past the prefix sniffer's reach)."},
			{"is_nef", "bool", "true if Nikon NEF / NRW (.nef, .nrw) — TIFF-based RAW. NEF is the primary Nikon SLR / mirrorless format; NRW is the Coolpix small-sensor variant, parsed by the same path."},
			{"is_arw", "bool", "true if Sony ARW / SRF / SR2 (.arw, .srf, .sr2) — TIFF-based RAW. ARW is the primary Sony Alpha / RX-series format; SRF / SR2 are older Cyber-shot variants, parsed by the same path."},
			{"is_dng", "bool", "true if Adobe DNG (.dng) — TIFF-based RAW, Adobe's universal RAW container. Used natively by Leica, Pentax, some Hasselblad, and Apple iPhone ProRAW captures."},
			{"is_raf", "bool", "true if Fujifilm RAF (.raf) — RAW format from Fuji X-series mirrorless cameras. Has a unique 15-byte `FUJIFILMCCD-RAW` magic at offset 0 — the most discriminative of the RAW magics."},
			{"is_orf", "bool", "true if Olympus / OM System ORF (.orf, .ori) — TIFF-based RAW with vendor-specific 4-byte magic words (`IIRO` / `IIRS` / `MMOR`) in place of the standard TIFF prefix."},
			{"is_rw2", "bool", "true if Panasonic RW2 (.rw2, .raw) — TIFF-based RAW from Panasonic Lumix / Leica cameras. Also claims `.raw` (Panasonic is the dominant `.raw` producer)."},
			{"is_live_photo", "bool", "true if HEIC still image has a sibling MOV with the same basename in the same directory — Apple Live Photo. Detection is one extra `os.Stat` per HEIC file. The paired video's path is at `live_photo_video_path`, its size at `live_photo_video_size`."},
			{"is_live_photo_video", "bool", "true if `.mov` file has a sibling HEIC with the same basename in the same directory — the video side of an Apple Live Photo pair. The MOV detects as `video/quicktime`; this predicate is restricted to the `.mov` extension to avoid future drift if quicktime's extension set widens. The paired still's path is at `live_photo_image_path`."},
			{"is_3d_model", "bool", "true if any 3D model file — content_type starts with `model3d/`. Umbrella over `is_stl` / `is_obj` / `is_gltf`. Surfaces vertex_count / face_count / has_normals / has_textures / materials / bounding_box where the format makes them cheap to read."},
			{"is_stl", "bool", "true if STereoLithography model (.stl) — both ASCII and binary variants. 3D-printing lingua franca. Binary STL surfaces vertex/face counts from its header in O(1); the bounding box comes from a vertex pass."},
			{"is_obj", "bool", "true if Wavefront OBJ model (.obj) — line-oriented ASCII mesh. has_textures fires when a `mtllib` reference is present; `materials` lists the `usemtl` names. (COFF .obj compiled-object files share the extension but produce empty attrs.)"},
			{"is_gltf", "bool", "true if glTF 2.0 model — `.gltf` (JSON) or `.glb` (binary container). The standard runtime / web 3D asset format. vertex/face counts come from the accessor table; bounding_box from the POSITION accessor min/max (no buffer read needed)."},
			{"md5", "string", "MD5 hex digest of the file's content (32 lowercase hex chars). Empty unless the caller opts in via --with-hashes / compute_hashes — hashing is not free. NSRL / VirusTotal / threat-intel-feed interop primary; consumed by hash-allowlist / hash-denylist matching when those flags are set. Cached alongside SHA1 + SHA256 in the index; single io.MultiWriter pass over the file so all three populate together."},
			{"sha1", "string", "SHA-1 hex digest of the file's content (40 lowercase hex chars). Same lifecycle as md5 — populated when --with-hashes / compute_hashes is set. NSRL ships MD5 + SHA1 as the canonical allowlist key; many forensic tools index by SHA1."},
			{"sha256", "string", "SHA-256 hex digest of the file's content (64 lowercase hex chars). Modern default; populated when --with-hashes / compute_hashes is set OR as a side effect of find_duplicates / find_near_duplicates. Stable across the file's (size, mtime) lifetime so the cached value survives any repeat walk."},
			{"created_at", "timestamp", "filesystem birth time of the file (when the inode was first created on the current filesystem). Populated for every file on modern filesystems (ext4 / APFS / NTFS / btrfs / xfs) via the same os.Stat call that reports size + mod_time — no extra I/O. Zero on filesystems / OSes that don't track it (rare). Use for forensic timeline reconstruction and (paired with mod_time) the is_btime_anomaly indicator. Distinct from disk_image_created_at, which is the timestamp embedded INSIDE a VHD / ISO file's own header."},
			{"metadata_changed_at", "timestamp", "filesystem ctime (last time the inode's metadata changed — permissions, ownership, hard-link count). Critical for tamper detection: an attacker chmod-ing a backdoor leaves no mod_time trace but does update ctime. Surfaced alongside created_at via the same syscall; zero when the OS doesn't expose ctime separately (Windows reports creation-time only)."},
			{"is_btime_anomaly", "bool", "fires when `created_at > mod_time` AND both are populated — the classic 'this file was placed here AFTER being modified elsewhere' indicator. Common causes: file restored from backup, copied between volumes (mod_time preserved, btime set to copy time), planted artefact, mount-time anomaly. False on normal files where the inode was created before any modifications."},
			{"magic_content_type", "string", "the content type detected from the file's first 512 bytes alone, ignoring extension. Populated only when the caller opts in via --check-disguised / check_disguised. Empty when no magic prefix matched OR when CheckDisguised wasn't set. Compare with extension_content_type to spot disguised files."},
			{"extension_content_type", "string", "the content type implied by the file's name (exact basename, then extension). Populated alongside magic_content_type when --check-disguised is set. Empty when no name-based match (extensionless files with unrecognised content)."},
			{"is_disguised", "bool", "fires when magic_content_type and extension_content_type are BOTH non-empty AND they disagree — the classic 'this .txt file contains a PE binary' / 'this .pdf is actually JavaScript' indicator. Requires --check-disguised. NB: legitimate name-vs-magic divergences (e.g. package.json matching manifest/node by name and json by magic) ALSO fire — pair with type predicates like `is_disguised && is_binary` for forensic-grade filtering."},
			{"is_known_good", "bool", "fires when the file's MD5 OR SHA1 OR SHA256 appears in the loaded hash allowlist (--hash-allowlist / hash_allowlist_path). Requires --with-hashes so the file's hashes are computed. The headline forensic-triage primitive: `!is_known_good` cuts an NSRL-allowlisted disk image's review surface by 80-95%."},
			{"is_known_bad", "bool", "fires when the file's MD5 OR SHA1 OR SHA256 appears in the loaded hash denylist (--hash-denylist / hash_denylist_path). Requires --with-hashes. Use with threat-intel feeds (IOC drops, internal known-malware lists) for first-pass triage."},
			{"similarity", "double", "cosine similarity (-1 to 1, typically 0 to 1 for embedding models) between this file's body embedding and the search call's query embedding. Populated when --semantic-query (CLI) / SemanticQuery (MCP) is set AND an Ollama embedding model is configured. 0 when no semantic query is set OR when the content type isn't text-shaped. Compose with type predicates and other filters: 'is_pdf && similarity > 0.7' / '!is_known_good && similarity > 0.5'."},
			{"bm25", "double", "Okapi BM25 keyword-relevance score of this file's body against the keyword query, with IDF computed over the candidate (post-filter) result set. Populated when --keyword-query / --hybrid (CLI) or keyword_query / hybrid (MCP) is set; 0 otherwise. Unbounded positive (higher = more relevant); only meaningful relative to the other results in the same call. Designed to compose with similarity in a --rank expression for hybrid keyword+semantic ranking: 'bm25*0.4 + similarity*0.6'. Issue #335."},
			{"git_last_commit_time", "timestamp", "UTC timestamp of the most recent git commit that touched this file. Populated when the caller opts in via --with-git (CLI) / with_git (MCP) AND the walk root is inside a git working tree AND the file is tracked. Zero when any of those don't hold. Use for repo-aware time queries that don't depend on filesystem mtimes (which on a fresh clone all reflect checkout time). Compose with timestamp() literals to filter to recent commits. Issue #271."},
			{"git_last_commit_author", "string", "git author name (per the commit's %an field) of the most recent commit that touched this file. Same lifecycle as git_last_commit_time. Use to find files most recently changed by a specific contributor. Issue #271."},
			{"git_last_commit_subject", "string", "first line of the most recent commit message touching this file. Same lifecycle as git_last_commit_time. Useful for spot-checking what kind of change last hit a file (e.g. filter on subjects beginning with 'fix:' or 'feat:'). Issue #271."},
			{"git_first_seen", "timestamp", "UTC timestamp of the oldest commit that touched this file in the current HEAD's history. Useful for finding recently-added files independent of filesystem mtime. Walks reachable history once per cache; renames are NOT followed (--no-renames) so a renamed file's first_seen reflects the rename commit, not the original creation. Issue #271."},
			{"git_commit_count", "int", "number of commits touching this file in the current HEAD's reachable history — a simple churn proxy. Useful for finding hot files: 'is_source && git_commit_count > 50'. 0 when the file isn't tracked or git data isn't loaded. Issue #271."},
			{"is_git_tracked", "bool", "fires when the file is in the git index (`git ls-files` membership). Requires --with-git / with_git. Use to filter out generated artefacts, build outputs, and untracked scratch files when reviewing a repo: 'is_source && is_git_tracked'. Issue #271."},
			{"is_git_ignored", "bool", "fires when the file is matched by .gitignore (or another standard git ignore source) AND not currently tracked. Requires --with-git / with_git. Tracked files are never reported as ignored even if a later .gitignore rule would exclude them — matches git's own check-ignore semantics. Use 'is_git_ignored' to find ignored build artefacts an agent should skip. Issue #271."},
			{"is_xattr_rich", "bool", "fires when the file has any extended attribute set. Requires `--with-xattrs` opt-in. Darwin-only — Linux / Windows xattr surfaces are out of scope for v1. Umbrella over the specific xattr predicates (`is_quarantined`, `has_finder_comment`) — useful when an agent only needs 'does this file have any xattr metadata' triage."},
			{"is_quarantined", "bool", "fires when the file carries a `com.apple.quarantine` xattr — Gatekeeper's record that the file was downloaded from the web (or arrived via mail / messaging / AirDrop). Requires `--with-xattrs`. The dominant forensic signal for 'this file came from outside this Mac'. Pair with `is_codesigned` for malware-detection one-liners: `is_mach_o && !is_codesigned && is_quarantined`."},
			{"xattr_keys", "list<str>", "sorted, deduplicated list of every extended-attribute key on the file (capped at 50). Requires `--with-xattrs`. Use `'com.apple.cs.CodeRequirements-1' in xattr_keys` for arbitrary-key membership filters."},
			{"xattr_count", "int", "total count of extended attributes on the file. Requires `--with-xattrs`. Useful as a coarse 'how much metadata does this file carry' triage signal."},
			{"quarantine_agent", "string", "human-readable name of the app that downloaded the file — `Safari`, `Google Chrome`, `Mail`, `Messages`, etc. Field 3 of the `com.apple.quarantine` xattr value. Requires `--with-xattrs`."},
			{"quarantine_event_id", "string", "per-event identifier from field 4 of the `com.apple.quarantine` xattr. Documented as the agent's bundle id but on modern macOS most browsers populate it with a UUID instead. Use as an opaque identifier for joining against other quarantine sources rather than as a bundle id."},
			{"quarantine_source_url", "string", "canonical source URL the file was downloaded from. Sourced primarily from the `com.apple.metadata:kMDItemWhereFroms` xattr (a binary plist containing the doc URL); falls back to field 5 of the quarantine xattr when WhereFroms is absent. Requires `--with-xattrs`."},
			{"quarantine_referrer_url", "string", "the page the user was on when they clicked the link that led to this download — second element of `kMDItemWhereFroms`. Requires `--with-xattrs`. Empty for direct downloads (e.g. clicking a link in an email)."},
			{"quarantine_download_date", "timestamp", "when the file was downloaded, decoded from field 2 of the `com.apple.quarantine` xattr (Unix-epoch seconds in hex on modern macOS). Requires `--with-xattrs`. Distinct from `mod_time` (which is set by the agent writing the file, typically the same moment) and `created_at` (the filesystem birth time)."},
			{"quarantine_user_approved", "bool", "fires when the user has explicitly approved running / opening this file via the Gatekeeper dialog. Decoded from flag bits 0x80 (LSQuarantineFlagsUserApproved) or 0x40 (LSQuarantineFlagsAlreadyApproved) in field 1. Requires `--with-xattrs`. Forensic signal: `is_quarantined && quarantine_user_approved && !is_codesigned` finds unsigned binaries the user explicitly let through."},
			{"finder_tags", "list<str>", "sorted list of Finder color tags and user-added text tags from the `com.apple.metadata:_kMDItemUserTags` xattr. Color tags appear as their canonical short name (`red`, `green`, etc.); user tags as-is. Requires `--with-xattrs`."},
			{"finder_color", "string", "dominant Finder color tag short name when set — `red` / `orange` / `yellow` / `green` / `blue` / `purple` / `gray`. First color tag wins when multiple colors are applied (rare). Requires `--with-xattrs`."},
			{"has_finder_comment", "bool", "fires when the file has a Finder comment (`com.apple.metadata:kMDItemFinderComment` xattr present). The comment text itself isn't surfaced in v1 — agents wanting it can check this flag and then read the xattr value. Requires `--with-xattrs`."},
		},
		TypeSpecific: []AttributeDoc{
			{"title", "string", "title (front-matter, markdown h1, HTML title, PDF title, EPUB, office, audio)"},
			{"body", "string", "full file body. Plain-text types (markdown/text/html/csv/json/xml/yaml/toml/source) are read directly; structured documents (office/epub/pdf, email .eml/.mbox, browser & chat exports, sqlite) are extracted to text on demand. Populated when --body (CLI) or include_body (MCP) is set; capped at body_max_bytes (default 1 MiB). Combine with CEL string methods: body.contains(\"X\"), body.matches(\"...\"), body.startsWith(\"Once upon\")."},
			{"word_count", "int", "word count (markdown body, plain text)"},
			{"line_count", "int", "line count (plain text)"},
			{"column_count", "int", "column count from header line (CSV/TSV)"},
			{"csv_columns", "list<str>", "header field names from the first CSV/TSV line"},
			{"page_count", "int", "page count (PDF)"},
			{"author", "string", "author (markdown front-matter, PDF, EPUB, office)"},
			{"language", "string", "locale code (EPUB, HTML <html lang>, markdown front-matter, PDF /Lang or XMP, office) OR programming-language name for source files (`go`, `python`, `javascript`, `typescript`, `rust`, `c`, `cpp`, `java`, `ruby`, `swift`, `kotlin`, `shell`, `lua`, `elixir`, `clojure`, `haskell`, `ocaml`, `zig`). Locale codes are 2-letter ISO 639-1; programming names are word tokens — they don't overlap."},
			{"root_element", "string", "root element name (XML)"},
			{"json_kind", "string", "'object' or 'array' (JSON)"},
			{"yaml_kind", "string", "'object' (mapping), 'array' (sequence), or 'scalar' — kind of the first YAML document's root node"},
			{"yaml_document_count", "int", "number of `---`-separated YAML documents in the file (1 for single-doc; >1 for K8s manifest bundles, etc.)"},
			{"module", "string", "Go module path declared in go.mod's `module` directive"},
			{"go_version", "string", "Go toolchain version declared in go.mod's `go` directive (e.g. '1.26.2')"},
			{"base_image", "string", "first `FROM <image>` directive in a Dockerfile / Containerfile"},
			{"project_types", "list<str>", "names of every project type the containing project matches (e.g. ['go', 'docker-compose']). Empty unless --resolve-projects (CLI) / resolve_projects=true (MCP) is set."},
			{"project_type", "string", "the first (alphabetically-sorted) match from project_types — convenience for `project_type == \"go\"` queries. Empty unless --resolve-projects is set."},
			{"is_static_site", "bool", "true when the file's resolved project type is a recognised static-site generator (`hugo`, `jekyll`, `eleventy`, `astro`, `gatsby`, `mkdocs`, `docusaurus`, `pelican`). Requires --resolve-projects."},
			{"img_width", "int", "image width in pixels"},
			{"img_height", "int", "image height in pixels"},
			{"is_c2pa", "bool", "true when the file carries a C2PA / Content Credentials provenance manifest (JPEG / PNG today). UNVERIFIED — reads the embedded JUMBF manifest without validating its cryptographic signature or trust chain (full validation needs c2pa-rs via CGO). Treat like EXIF: what the file claims, not an authenticated fact. Issue #374."},
			{"c2pa_claim_generator", "string", "the tool that created/edited the asset, from the C2PA claim (e.g. 'Adobe Firefly', 'make_test_images/0.33.1 c2pa-rs/0.33.1'). Empty when no manifest. Unverified — see is_c2pa. By tool: is_c2pa && c2pa_claim_generator.contains('Firefly')."},
			{"c2pa_title", "string", "the C2PA claim's dc:title (the asset's declared title). Empty when no manifest."},
			{"c2pa_format", "string", "the C2PA claim's dc:format (declared media type, e.g. image/jpeg). Empty when no manifest."},
			{"c2pa_ai_generated", "bool", "true when the C2PA manifest declares AI-generated content — a c2pa.actions assertion whose digitalSourceType is trainedAlgorithmicMedia or compositeWithTrainedAlgorithmicMedia. Find AI-generated images: is_image && c2pa_ai_generated. Unverified claim (see is_c2pa); absence does NOT mean 'not AI' — most files carry no manifest."},
			{"c2pa_signed_by", "string", "the COSE_Sign1 signer's leaf x509 certificate common name (Subject CN, falling back to Organization), from the C2PA signature. Empty when no manifest or no signer cert. UNVERIFIED — the certificate chain is NOT validated against the C2PA trust list (full validation needs c2pa-rs via CGO); this is the CLAIMED signer, like an unverified email From header. Issue #375. By signer: is_c2pa && c2pa_signed_by.contains('Adobe')."},
			{"c2pa_signed_at", "timestamp", "the signing time from the RFC 3161 timestamp embedded in the C2PA signature envelope (sigTst). Zero when no manifest or no timestamp. Unverified claim (see c2pa_signed_by). Recently-signed credentials: is_c2pa && c2pa_signed_at > timestamp('2024-01-01T00:00:00Z')."},
			{"camera_make", "string", "EXIF camera make (JPEG/TIFF/HEIC/PNG)"},
			{"camera_model", "string", "EXIF camera model"},
			{"lens", "string", "EXIF lens model"},
			{"taken_at", "timestamp", "EXIF DateTimeOriginal — image capture time"},
			{"orientation", "int", "EXIF orientation tag (1-8)"},
			{"gps_lat", "double", "GPS latitude in decimal degrees (north positive)"},
			{"gps_lon", "double", "GPS longitude in decimal degrees (east positive)"},
			{"iso", "int", "EXIF ISO sensitivity"},
			{"focal_length", "double", "EXIF focal length in mm"},
			{"f_stop", "double", "EXIF F-number (aperture)"},
			{"exposure_time", "double", "EXIF exposure time in seconds"},
			{"artist", "string", "audio artist tag (ID3v2 TPE1 / Vorbis ARTIST / iTunes ©ART)"},
			{"album", "string", "audio album tag"},
			{"album_artist", "string", "audio album-artist tag (compilations)"},
			{"composer", "string", "audio composer tag"},
			{"year", "int", "audio release year"},
			{"track", "int", "audio track number"},
			{"genre", "string", "audio genre tag"},
			{"duration", "double", "audio duration in seconds (FLAC STREAMINFO / MP3 Xing / OGG granule / MP4 mvhd)"},
			{"bitrate", "int", "average bitrate in kbps (computed file_size * 8 / duration / 1000) — applies to audio and video"},
			{"nominal_bitrate", "int", "codec/container-stored bitrate in kbps, distinct from the computed average. Audio: MP3 first-frame bitrate, OGG Vorbis bitrate_nominal, M4A esds avgBitrate (with maxBitrate fallback). Video: MP4 btrt avgBitrate, MKV/WebM TrackEntry Bitrate, AVI avih maxBytesPerSec. FLAC max_frame_size is not surfaced — it doesn't translate cleanly to kbps without frame timing."},
			{"color_primaries", "string", "video colour primaries — 'bt709' (HD), 'bt2020' (HDR / wide-gamut), 'p3' (DCI-P3 / Display P3), or '' if unspecified. Decoded from MP4 colr nclx or MKV Colour element."},
			{"color_transfer", "string", "video transfer characteristics — 'bt709' (SDR), 'pq' (SMPTE ST 2084 — HDR10), 'hlg' (Hybrid Log-Gamma — broadcast HDR), or '' if unspecified."},
			{"is_hdr", "bool", "true when transfer is PQ (HDR10 / HDR10+ / Dolby Vision base layer) or HLG. The canonical 'this video is HDR' signal."},
			{"subtitles", "bool", "true when at least one subtitle / closed-caption track is present (MP4 text/subt/sbtl/clcp tracks; MKV TrackType 17). Empty for AVI."},
			{"subtitle_languages", "list<str>", "ISO 639-2 language codes from each subtitle track in declaration order. Empty string when language is unspecified or marked 'und'."},
			{"replaygain_track_gain", "double", "ReplayGain track gain in dB (negative = quieter, positive = louder). Sourced from Vorbis comments (FLAC + OGG REPLAYGAIN_TRACK_GAIN), ID3v2 TXXX user-defined-text frames (MP3), and M4A iTunes ---- atoms (com.apple.iTunes namespace)."},
			{"replaygain_album_gain", "double", "ReplayGain album gain in dB. Same sources / coverage as replaygain_track_gain — Vorbis comments, ID3v2 TXXX, and M4A iTunes ---- atoms."},
			{"entry_count", "int", "archive entry count — number of files / directories inside a ZIP, TAR, or TAR.GZ. Always 1 for standalone .gz (gzip carries one stream per RFC 1952)."},
			{"uncompressed_size", "int", "archive total uncompressed size in bytes — sum of per-entry sizes for ZIP / TAR / TAR.GZ. For standalone .gz reads the 4-byte ISIZE footer; this is mod 2^32 so files whose payload exceeds 4 GiB report a wrapped value (matches `gzip -l`)."},
			{"top_level_entries", "list<str>", "archive root-level entry names, sorted and deduplicated. A traditional 'tarball-with-one-root-dir' has a single element; a sprawling archive that explodes into the working directory has many."},
			{"has_root_dir", "bool", "true when the archive has a single top-level entry — the Unix convention. Useful for spotting ZIP-bombs (false → many top-level entries that would all extract into the cwd)."},
			{"architectures", "list<str>", "compiled-binary CPU architectures (canonical names: x86_64, arm64, i386, arm, ppc64, riscv64, …). Length 1 for thin ELF / Mach-O / PE; length ≥ 2 for fat (universal) Mach-O."},
			{"bitness", "int", "compiled-binary bitness — 32 or 64. For fat Mach-O, reflects the first slice."},
			{"binary_format", "string", "compiled-binary format: 'elf', 'mach-o', or 'pe'. Mirrors the content-type subtype lifted to a CEL string."},
			{"binary_type", "string", "compiled-binary kind: 'executable', 'shared_library', 'object', 'core', or 'unknown'. Cross-format normalisation of ELF e_type, Mach-O Type, and PE Characteristics."},
			{"is_dynamically_linked", "bool", "true when the binary depends on shared libraries. ELF: PT_INTERP or PT_DYNAMIC present. Mach-O: any LC_LOAD_DYLIB load command. PE: non-empty import directory."},
			{"is_stripped", "bool", "true when the symbol table is absent or empty. ELF: Symbols() returns ErrNoSymbols. Mach-O: Symtab nil or empty. PE: IMAGE_FILE_DEBUG_STRIPPED bit set or empty COFF symbols."},
			{"entry_point", "int", "compiled-binary entry point — virtual address from ELF Entry / PE AddressOfEntryPoint. Zero for shared libraries, object files, and Mach-O (which reports entry-via-LC_MAIN offset that debug/macho doesn't expose)."},
			{"is_codesigned", "bool", "true if the Mach-O has a non-empty `LC_CODE_SIGNATURE` load command. macOS-specific — ELF / PE always return false even when they carry signatures in their own formats (Authenticode / GnuPG sigs are separate)."},
			{"is_apple_signed", "bool", "true if the binary's CodeDirectory has an empty Team ID AND is not adhoc-signed AND is_codesigned — the v1 heuristic for Apple first-party binaries (Apple's own binaries don't carry a Developer ID team_id; adhoc-signed binaries are flagged explicitly). False positives may occur on locally re-signed binaries with empty team_id; full cert-chain parsing is a follow-up that would refine this."},
			{"is_third_party_signed", "bool", "true if the binary's CodeDirectory has a non-empty Team ID — i.e. signed with an Apple Developer ID account. Mutually exclusive with `is_apple_signed`."},
			{"codesign_identifier", "string", "CodeDirectory `identifier` field — usually the bundle id (e.g. `com.apple.Safari`, `com.anthropic.claudefordesktop.helper`). Distinct from `plist_bundle_identifier`: the codesign identifier is what the kernel validates against; the plist identifier is what the OS uses for app launches. They almost always match but a re-signed binary can disagree."},
			{"codesign_team_id", "string", "Apple Developer Team ID (10-char alphanumeric, e.g. `EQHXZ8M8AV` for Anthropic). Empty for Apple first-party binaries and adhoc-signed binaries. Distinct per developer account — use to inventory binaries by vendor."},
			{"codesign_hash_type", "string", "CodeDirectory hash algorithm: 'sha1' (legacy), 'sha256' (modern default), 'sha256-truncated', 'sha384', 'sha512'. Modern Apple binaries use sha256."},
			{"codesign_hardened_runtime", "bool", "true if the `CS_RUNTIME` flag is set in the CodeDirectory — the binary opts into Apple's hardened runtime (JIT disabled by default, library validation enabled, runtime entitlements required). Notarization requires this flag."},
			{"codesign_library_validation", "bool", "true if the `CS_LIBRARY_VALIDATION` flag is set — the binary will only load libraries signed by the same Team ID (or Apple). Hardened-runtime binaries get this by default unless they explicitly disable it via the `com.apple.security.cs.disable-library-validation` entitlement."},
			{"codesign_killed", "bool", "true if the `CS_KILL` flag is set — the kernel terminates the process on any signature validation failure. Set by default for hardened-runtime binaries."},
			{"codesign_adhoc", "bool", "true if the `CS_ADHOC` flag is set — the binary was self-signed without a real cert chain. Common for local development builds, `codesign -s -` invocations, and some homebrew binaries."},
			{"entitlements", "list<str>", "Sorted list of entitlement keys from the embedded entitlements plist (slot 5 / magic `0xfade7171`). Capped at 1024 keys; covers both Apple-defined entitlements (`com.apple.security.*`) and custom keys. Empty when the binary has no entitlements blob."},
			{"entitlement_app_sandbox", "bool", "true if `com.apple.security.app-sandbox` is set true in the entitlements plist. Required for Mac App Store apps; rare outside that channel. Sandboxed apps are confined to a per-bundle container directory and explicit file-access entitlements."},
			{"entitlement_full_disk_access", "bool", "true if the binary has any entitlement granting full filesystem access — `com.apple.security.files.all`, `com.apple.security.files.user-selected.read-write`, or the private `com.apple.private.tcc.allow`. Forensic-grade indicator for 'this binary can read every file the user can'."},
			{"entitlement_network_client", "bool", "true if `com.apple.security.network.client` is true — sandboxed binaries explicitly declaring outbound network access. Unsandboxed binaries don't need this entitlement; the check is meaningful only when paired with `entitlement_app_sandbox`."},
			{"entitlement_network_server", "bool", "true if `com.apple.security.network.server` is true — sandboxed binaries explicitly declaring inbound (listen-port) network access. Common for daemons; rare for GUI apps."},
			{"email_to", "list<str>", "RFC 5322 To header — addresses only (display names dropped to keep the list shape predictable for `\"alice@example.com\" in email_to` queries). For mbox archives, reflects the FIRST message."},
			{"email_cc", "list<str>", "RFC 5322 Cc header — addresses only. For mbox archives, reflects the FIRST message."},
			{"email_message_id", "string", "RFC 5322 Message-ID header (angle brackets stripped). For mbox archives, reflects the FIRST message."},
			{"email_in_reply_to", "string", "RFC 5322 In-Reply-To header (angle brackets stripped). For mbox archives, reflects the FIRST message."},
			{"sent_at", "timestamp", "email Date header parsed via mail.ParseDate. Mirrors taken_at for images. For mbox archives, reflects the FIRST message."},
			{"attachment_count", "int", "count of multipart parts that carry Content-Disposition: attachment or a filename parameter. Zero for non-multipart messages. Walks one level deep — nested multiparts are aggregated into their parent."},
			{"email_count", "int", "mbox archive — number of messages in the archive (count of `^From ` separator lines). Always 1 for single .eml files."},
			{"loc", "int", "source-code lines of code — non-blank, non-comment lines. Mixed lines (code with trailing `// comment`) count as code; lines that BEGIN with a comment marker count as comment. String literals containing `//` or `/*` are treated as code (no string-aware parsing)."},
			{"comment_loc", "int", "source-code comment lines — lines that begin with the language's line-comment marker, plus every line wholly inside a block comment. For OCaml (no line comments) only block-comment lines are counted."},
			{"blank_loc", "int", "source-code blank lines — empty or whitespace-only. A blank line inside a block comment counts as blank, matching the cloc / tokei convention."},
			{"functions", "list<string>", "top-level + nested function / method names defined in this source file. Populated for source/go (via stdlib AST) and the 15 other tree-sitter-backed languages — Python / Java / C# / PHP / Perl / R / MATLAB / Scala / Rust / TypeScript / JavaScript / Ruby / Swift / Kotlin / C / C++ (all via an embedded tree-sitter grammar since #365). For Go captures both top-level func and receiver-bound methods (bare method name, not receiver-qualified). Other languages leave this empty. Composes with the `in` operator — agents asking 'where is ProcessOrder defined?' do `is_source && 'ProcessOrder' in functions`."},
			{"type_names", "list<string>", "top-level + nested type names defined in this source file. Populated for source/go (type declarations, including aliases + generics), source/python (class), source/java (class / interface / enum / record / @interface), and the tree-sitter languages (Scala / C# / Java / PHP / Rust / TypeScript / JavaScript / Ruby / Swift / Kotlin / C / C++ — classes / structs / traits / interfaces / enums / protocols / records). Renamed from `types` to avoid CEL-name collisions. Composes with `in` — `is_source && 'Handler' in type_names` for define-X queries."},
			{"imports", "list<string>", "import paths / module names this source file declares. Populated for source/go (full import paths via go/ast, e.g. net/http), source/python (the module side of import X and from X import ... — captures X), and the other tree-sitter languages (Java / C# / PHP / Perl / R / MATLAB / Scala / Rust / TS / JS / Ruby / Swift / Kotlin / C / C++ — each grammar's import-shape node; R's library()/require() calls, C/C++ #include paths). Surfaces in the wire format as match.imports so 'fields: imports' projection works. Find files using a dependency: `is_source && 'github.com/spf13/cobra' in imports`. Reverse-deps inside this repo: `is_source && language == 'go' && imports.exists(p, p.endsWith('internal/index'))`. Issue #275."},
			{"references", "list<string>", "distinct names of every symbol this source file *uses*. Includes call sites (`pkg.Foo()` / `x.Method()` capture `Foo` / `Method`, not receiver-qualified); for Go also function/method VALUES passed as call arguments (issue #421 — `AddTool(s, t, h.handler)` references `handler`), so a callback-registered function counts as used. It ALSO includes TYPE usages — a type named as a field type, parameter / result, variable type, or generic argument (issue #398) — so a type used only as a field type counts as referenced. Type usages cover Go (via go/ast, incl. composite-literal / embedding / type-assertion positions) plus the statically-typed tree-sitter languages (Rust / TypeScript / Python / Java / C# / C / C++ / Kotlin / Swift / Scala / PHP); JavaScript / Ruby / Perl / R / MATLAB have no static type annotations, so they stay call-only. Powers the who_calls / dead_code tools. Find users of a symbol: `is_source && 'ProcessOrder' in references`. Issues #363 / #398 / #421."},
			{"max_complexity", "int", "highest cyclomatic complexity of any function in this source file (gocyclo-style: 1 + branch points — if / for / while / case / && / ||). File-level hotspot signal — `is_source && max_complexity > 15` finds the gnarly files. Populated for source/go (stdlib AST) + the tree-sitter languages (Rust / TypeScript / JavaScript / Ruby / Swift / Kotlin / C / C++); 0 for others. Directionally accurate for ranking hotspots (exact value depends on per-grammar node coverage); drill into individual functions with the `complexity` tool. Issue #364."},
			{"cell_count", "int", "total number of cells/paragraphs in a notebook (Jupyter .ipynb / Zeppelin .zpln)"},
			{"code_cell_count", "int", "notebook code cells. For Jupyter: cells whose cell_type == \"code\". For Zeppelin: paragraphs whose editor language isn't markdown and whose text doesn't begin with %md."},
			{"markdown_cell_count", "int", "notebook markdown cells. For Jupyter: cells whose cell_type == \"markdown\". For Zeppelin: paragraphs whose editor language is markdown or whose text begins with %md."},
			{"kernel", "string", "notebook kernel/interpreter — Jupyter metadata.kernelspec.name (falling back to display_name); Zeppelin defaultInterpreterGroup."},
			{"sample_rate", "int", "audio sample rate in Hz"},
			{"channels", "int", "audio channel count (1 = mono, 2 = stereo, etc.)"},
			{"bit_depth", "int", "audio bits per sample (FLAC STREAMINFO / MP4 stsd sample_size; zero for MP3 / OGG which don't store it)"},
			{"video_codec", "string", "video codec (h264, h265, av1, vp9, vp8, mpeg4, etc.)"},
			{"audio_codec", "string", "audio codec for the audio track in a video container (aac, mp3, opus, vorbis, etc.)"},
			{"video_width", "int", "video frame width in pixels"},
			{"video_height", "int", "video frame height in pixels"},
			{"frame_rate", "double", "video frame rate in fps"},
			{"rotation", "int", "video display rotation in degrees (0 / 90 / 180 / 270) decoded from the MP4 tkhd matrix; 0 for non-rotated, non-MP4 formats, or non-pure-rotation matrices"},
			{"disk_image_format", "string", "disk-image format identifier — 'udif' (DMG), 'iso9660' (ISO), 'vhd-fixed' / 'vhd-dynamic' / 'vhd-differencing' (VHD), 'vhdx' (VHDX), 'vmdk-sparse' (VMDK), 'qcow2' (QCOW2), or 'wim' (WIM). Set whenever content_type starts with 'disk-image/'."},
			{"virtual_size", "int", "disk-image logical capacity in bytes — the size the image presents when mounted, not the compressed/sparse on-disk footprint. DMG: SectorCount × 512. ISO: volume_space_size × 2048. VHD: CurrentSize. VHDX: VirtualDiskSize metadata item (best-effort; 0 if region walk fails). VMDK: capacity × 512. QCOW2: header `size` field. WIM: 0 (file-level archive, not a disk — use the always-on `size` attribute for on-disk footprint)."},
			{"disk_type", "string", "disk-image sub-format. VHD: 'fixed' / 'dynamic' / 'differencing'. VMDK: 'sparse' / 'sparse-compressed'. Empty for DMG / ISO / VHDX / QCOW2 / WIM."},
			{"volume_label", "string", "ISO 9660 volume identifier from the primary volume descriptor (32 chars, trimmed)."},
			{"disk_image_created_at", "timestamp", "disk-image creation timestamp parsed from inside the file's own header. VHD: TimeStamp field (seconds since 2000-01-01 UTC). ISO: volume_creation_date_and_time from the PVD. Empty for other disk-image formats and non-disk-image files. (NOT the filesystem-level birth time — see `created_at` for that.)"},
			{"cluster_bits", "int", "QCOW2 cluster size as power of 2 (cluster size in bytes = 1 << cluster_bits). Typical values 16 (64 KiB) or 17 (128 KiB)."},
			{"is_encrypted", "bool", "QCOW2 encryption flag — true when crypt_method != 0 (1 = AES, 2 = LUKS). False (or absent) for unencrypted images and for other formats."},
			{"image_count", "int", "WIM archive image count — number of distinct system images contained in a WIM file."},
			{"package_format", "string", "install-package format identifier — 'xar' (macOS pkg), 'deb' (Debian), 'rpm' (Red Hat), 'appimage' (Linux portable). Set whenever content_type starts with 'install/'."},
			{"package_name", "string", "install-package name extracted from format-specific metadata. RPM: parsed from the Lead's <name>-<version>-<release> field. DEB and PKG don't carry the name in the file header — extracting it requires walking the inner control.tar.* or TOC respectively (out of scope for v1)."},
			{"package_version", "string", "install-package version. RPM: second-to-last `-`-delimited segment of the Lead name. Empty for DEB / PKG / AppImage in v1."},
			{"package_release", "string", "install-package release / build identifier. RPM: last `-`-delimited segment of the Lead name (often distro-specific, e.g. '1.el9'). Empty for other formats."},
			{"package_arch", "string", "install-package target architecture, canonical lowercase ('i386', 'x86_64', 'aarch64', 'ppc64le', 'riscv64', etc). RPM: decoded from the Lead's archnum field. Empty for other formats in v1."},
			{"package_kind", "string", "install-package classification. RPM: 'binary' or 'source'. PKG: 'macos-installer'. AppImage: 'linux-portable'. DEB: 'binary' (the only standard kind for .deb files)."},
			{"appimage_version", "int", "AppImage on-disk format version (1 or 2). v2 is the current format; v1 was superseded in 2017."},
			{"license_id", "string", "SPDX license identifier detected by scanning the body of a LICENSE / LICENCE / COPYING / UNLICENSE file. Recognised: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, GPL-3.0, GPL-2.0, LGPL-3.0, LGPL-2.1, AGPL-3.0, MPL-2.0, ISC, Unlicense, CC0-1.0, BSL-1.0. Empty when the file doesn't match a recognised license. .md license variants (e.g. LICENSE.md) currently detect as markdown and don't populate license_id — use is_markdown && name.startsWith(\"LICENSE\") as a fallback."},
			{"target_path", "string", "for symlinks, the raw link target as recorded on disk (relative or absolute — whatever the user passed to `ln -s`). Empty for non-symlinks. Surface alongside is_symlink and is_broken_symlink to audit dangling references, follow chains, or filter out symlinked duplicates."},
			{"plist_format", "string", "Apple property-list encoding — `'binary'` for `bplist00` files (the default since ~10.5 for `~/Library/Preferences/*.plist`) or `'xml'` for human-readable XML plists (older preferences, hand-edited files, Info.plist for many open-source apps). Both decode through the same howett.net/plist parser."},
			{"plist_root_kind", "string", "Top-level object type of the parsed plist — `'dict'` (overwhelmingly common — every Info.plist, every LaunchAgent, every Preferences file), `'array'`, `'string'`, `'bool'`, `'integer'`, `'real'`, `'data'`. Empty when the parser couldn't classify."},
			{"plist_kind", "string", "Curated label from a path-based registry: `'info'` (Info.plist for app / kext bundles), `'launch-agent'` (path under `LaunchAgents/`), `'launch-daemon'` (path under `LaunchDaemons/`), `'preferences'` (path under `Preferences/`), `'webloc'` (Safari saved-page link — dict with `URL` key). Empty when no registry entry matches; agents can filter on `plist_kind == \"\"` to surface unrecognised plists for triage."},
			{"plist_bundle_identifier", "string", "Apple bundle identifier from `CFBundleIdentifier` (Info.plist) — e.g. `com.apple.Safari`, `com.anthropic.claude`. The canonical app-identity key on macOS / iOS / tvOS / watchOS."},
			{"plist_bundle_name", "string", "Human-readable bundle name from `CFBundleDisplayName` (preferred — what Finder shows) or `CFBundleName` (fallback). E.g. `Safari`, `Claude`."},
			{"plist_bundle_version", "string", "Build / internal bundle version from `CFBundleVersion`. Apple's convention: monotonically increasing build number (e.g. `19618.2.12.10.9`). Distinct from `plist_bundle_short_version` which is the user-facing semver."},
			{"plist_bundle_short_version", "string", "User-facing semantic version from `CFBundleShortVersionString` (e.g. `17.2.1`, `2024.1`). What an app's About dialog shows."},
			{"plist_executable", "string", "Bundle executable filename from `CFBundleExecutable` (the file inside `<App>.app/Contents/MacOS/` that the system actually launches)."},
			{"plist_min_os_version", "string", "Minimum OS version from `LSMinimumSystemVersion` (e.g. `14.0`). Set on app bundles; pair with `plist_kind == 'info'` to find apps blocking an OS upgrade."},
			{"plist_label", "string", "LaunchAgent / LaunchDaemon job label from `Label` (e.g. `com.apple.afpfs_afpLoad`, `homebrew.mxcl.postgresql`). The canonical job identifier launchd uses."},
			{"plist_program", "string", "LaunchAgent / LaunchDaemon executable from `Program` (preferred — single absolute path) or `ProgramArguments[0]` (fallback — first element of the argv array). The executable launchd actually runs."},
			{"plist_program_arguments", "list<str>", "LaunchAgent / LaunchDaemon argv from `ProgramArguments`. First element is conventionally the executable path (mirrored to `plist_program` when `Program` is absent); rest are runtime args. Empty when the plist uses the `Program` key only."},
			{"plist_run_at_load", "bool", "LaunchAgent / LaunchDaemon persistence flag from `RunAtLoad`. True means the job starts immediately on system / user login — the dominant persistence indicator on macOS. Field is `omitempty` so `false` (job runs only on demand) is distinguishable from \"not set\"."},
			{"plist_keep_alive", "bool", "LaunchAgent / LaunchDaemon persistence flag from `KeepAlive`. True means launchd restarts the job whenever it exits — paired with `plist_run_at_load == true` this is the strongest persistence pattern. Field is `omitempty` so `false` is distinguishable from \"not set\"."},
			{"bytecode_format", "string", "VM bytecode format identifier — 'jvm' (Java .class), 'python' (CPython .pyc / .pyo), 'wasm' (WebAssembly). Set whenever content_type starts with 'bytecode/'."},
			{"runtime_version", "string", "VM bytecode runtime version, human-readable. JVM: 'Java 8'..'Java 24' (mapped from the .class major version per JVMS §4.1). Python: 'Python 3.7'..'Python 3.14' (mapped from the .pyc magic number table). WASM: 'WebAssembly 1.0' (from the module's u32 version header)."},
			{"class_name", "string", "JVM .class — the fully-qualified class name (e.g. 'java/lang/String') resolved through CONSTANT_Class → CONSTANT_Utf8 in the constant pool."},
			{"super_class", "string", "JVM .class — the superclass's fully-qualified name. Usually 'java/lang/Object' for most application classes."},
			{"interfaces", "list<str>", "JVM .class — fully-qualified names of every interface the class implements (e.g. ['java/io/Serializable'])."},
			{"method_count", "int", "JVM .class — number of methods declared on the class (including synthetic / bridge methods generated by javac)."},
			{"field_count", "int", "JVM .class — number of fields declared on the class."},
			{"access_flags", "list<str>", "JVM .class — canonical names of the class-level access flags ('public', 'final', 'super', 'interface', 'abstract', 'synthetic', 'annotation', 'enum', 'module'). Same vocabulary the JVMS access_flags table defines."},
			{"python_version", "string", "Python .pyc — the bytecode's source Python release (e.g. '3.11'). Resolved from the 2-byte LE magic number per CPython's MAGIC_NUMBER table."},
			{"source_mtime", "timestamp", "Python .pyc — the source .py file's mtime that was current when the .pyc was compiled. Zero for hash-based .pyc files (PEP 552, Python 3.7+ when SOURCE_DATE_EPOCH or --check-hash-based-pycs is in play)."},
			{"wasm_version", "int", "WebAssembly module format version. Currently 1 is the only released version of the binary spec."},
			{"section_count", "int", "WebAssembly module section count — how many top-level sections (type, import, function, table, memory, global, export, start, element, code, data, datacount, custom) the module declares."},
			{"import_count", "int", "WebAssembly module — number of entries in the Import section. Useful for spotting modules with unusually large host-binding surfaces."},
			{"export_count", "int", "WebAssembly module — number of entries in the Export section. Zero for modules used as pure libraries (typically you'd expect 1+ for invocation surface)."},
			{"science_format", "string", "scientific-data format identifier — 'fits' (Flexible Image Transport System). Set whenever content_type starts with 'science/'."},
			{"telescope", "string", "FITS TELESCOP keyword — telescope or observatory name (e.g. 'HST', 'JWST', 'VLT', 'Gemini-North'). Pulled verbatim from the primary HDU."},
			{"instrument", "string", "FITS INSTRUME keyword — detector / instrument name (e.g. 'WFC3', 'NIRCam', 'STIS', 'X-shooter')."},
			{"object", "string", "FITS OBJECT keyword — observed target name (e.g. 'M31', 'NGC 1234', 'Vega'). Also lifted to the shared `title` attribute for cross-family vocabulary."},
			{"observer", "string", "FITS OBSERVER keyword — observer / PI name. Also lifted to the shared `author` attribute."},
			{"date_obs", "string", "FITS DATE-OBS keyword — raw observation date string from the header. Kept verbatim for exact-match filters; the parsed timestamp is exposed via the shared `taken_at` attribute (ISO 8601, falling back to `YYYY-MM-DD`)."},
			{"exptime", "double", "FITS EXPTIME keyword — exposure time in seconds."},
			{"filter", "string", "FITS FILTER keyword — bandpass / filter wheel position (e.g. 'F814W', 'g', 'Halpha')."},
			{"airmass", "double", "FITS AIRMASS keyword — atmospheric airmass at mid-exposure (1.0 = zenith; higher = closer to horizon)."},
			{"ra", "double", "FITS right ascension in degrees. Prefers CRVAL1 (WCS standard) and falls back to RA (older convention) when CRVAL1 is absent."},
			{"dec", "double", "FITS declination in degrees. Prefers CRVAL2 (WCS) over DEC."},
			{"bitpix", "int", "FITS BITPIX keyword — pixel data type. 8 / 16 / 32 / 64 = unsigned / signed integer of that width; -32 / -64 = IEEE float32 / float64 (negative values denote floating-point)."},
			{"naxis", "int", "FITS NAXIS keyword — dimensionality of the data array (0 = no data unit / metadata-only HDU; 1 = spectrum; 2 = image; 3 = cube / RGB; ≥4 = hypercube / IFU stack)."},
			{"naxis1", "int", "FITS NAXIS1 keyword — first-axis length (typically image width in pixels for 2D arrays)."},
			{"naxis2", "int", "FITS NAXIS2 keyword — second-axis length (typically image height for 2D arrays)."},
			{"hdu_count", "int", "FITS file — number of Header-Data Units (HDUs). 1 for single-HDU files; 2+ for multi-extension FITS (MEF) used by mosaic instruments and complex pipelines. Capped at 100 to defend against adversarial headers."},
			{"fits_kind", "string", "FITS primary HDU classification — 'image' (SIMPLE=T with NAXIS>0, or XTENSION=IMAGE), 'table' (XTENSION=TABLE), 'binary-table' (XTENSION=BINTABLE), 'primary' (metadata-only primary HDU with NAXIS=0)."},
			{"votable_version", "string", "VOTable IVOA standard version declared in the root `<VOTABLE version=\"...\">` attribute (e.g. '1.3', '1.4', '1.5')."},
			{"table_count", "int", "VOTable — number of `<TABLE>` elements across all `<RESOURCE>` blocks in the file."},
			{"total_rows", "int", "VOTable — sum of `<TABLE nrows=\"...\">` attributes across every table. Tables without `nrows` contribute 0 (row counting via `<TR>` walk is out of scope to avoid full-table iteration on large catalogs)."},
			{"field_names", "list<str>", "VOTable — every `<FIELD name=\"...\">` column name across all tables in declaration order. Capped at 10000 entries to defend against adversarial inputs."},
			{"field_units", "list<str>", "VOTable — every `<FIELD unit=\"...\">` value, parallel to field_names by index. Empty string for fields without a declared unit."},
			{"field_ucds", "list<str>", "VOTable — every `<FIELD ucd=\"...\">` value (Unified Content Descriptor, IVOA semantic classification), parallel to field_names by index."},
			{"votable_data_format", "string", "VOTable — first table's `<DATA>` child element name lowercased: 'tabledata' (XML row payload), 'binary' / 'binary2' (base64-encoded streams), 'fits' (embedded FITS file). Empty when the file's first table has no `<DATA>` element."},
			{"hdf5_format_version", "int", "HDF5 superblock format version (0, 1, 2, or 3). v0 / v1 are the legacy libhdf5-1.6 / 1.8 layouts; v2 / v3 are the compact post-1.10 format. Useful for downstream tooling that needs to gate behaviour on superblock generation. Always populated when is_hdf5 fires."},
			{"hdf5_size_of_offsets", "int", "HDF5 superblock Size of Offsets field — byte width of file-offset addresses. Typically 8 (64-bit); 4 on 32-bit-era files. Empty when the superblock is corrupt or the value exceeds the 16-byte sanity cap."},
			{"hdf5_size_of_lengths", "int", "HDF5 superblock Size of Lengths field — byte width of length fields. Typically 8; same v1 scope semantics as `hdf5_size_of_offsets`."},
			{"pds_version", "string", "PDS label version — 'PDS3' (legacy PVL labels — Voyager / Galileo / Cassini / Mars rovers through Curiosity) or 'PDS4' (current XML standard — Perseverance, Lucy, OSIRIS-REx)."},
			{"mission_name", "string", "PDS — mission name. PDS3 MISSION_NAME keyword (e.g. 'MARS RECONNAISSANCE ORBITER'). PDS4 Observation_Area > Investigation_Area > name (e.g. 'Mars 2020 Perseverance Rover')."},
			{"spacecraft_name", "string", "PDS — spacecraft / instrument-host name. PDS3 SPACECRAFT_NAME or INSTRUMENT_HOST_NAME. PDS4 Observing_System_Component with type=Host or type=Spacecraft (first match wins)."},
			{"instrument_name", "string", "PDS — instrument name. PDS3 INSTRUMENT_NAME or INSTRUMENT_ID keyword. PDS4 Observing_System_Component with type=Instrument (first match wins)."},
			{"target_name", "string", "PDS — observed target. PDS3 TARGET_NAME keyword (e.g. 'MARS', 'TITAN', 'BENNU'). PDS4 Target_Identification > name."},
			{"product_id", "string", "PDS — unique product identifier. PDS3 PRODUCT_ID keyword. PDS4 logical_identifier (LID URN)."},
			{"start_time", "string", "PDS — observation / acquisition start. Raw string from PDS3 START_TIME or PDS4 Time_Coordinates > start_date_time. Parsed timestamp also exposed via the shared `taken_at` attribute (ISO 8601 with fallback formats)."},
			{"cdf_version", "string", "CDF format version + release + increment joined with dots (e.g. '3.8.0'). Surfaces '3.x' as a sentinel when the magic matched but the CDR header was too short to read the full version triple."},
			{"cdf_encoding", "string", "CDF data encoding canonical short name: 'network' / 'sun' / 'vax' / 'decstation' / 'sgi' / 'ibmpc' / 'ibmrs' / 'mac' / 'hp' / 'next' / 'alpha-osf1' / 'alpha-vms-d' / 'alpha-vms-g' / 'alpha-vms-i' / 'arm-little' / 'arm-big'. Most modern files are 'network' or 'ibmpc'. Empty when the encoding integer isn't in the canonical table."},
			{"cdf_majority", "string", "CDF variable-array majority — 'row' (C / row-major) or 'column' (Fortran / column-major). Decoded from the CDR Flags bit 1."},
			{"variable_count", "int", "CDF — total number of variables in the file (NrVars + NzVars from the GDR — r-variables + z-variables). Populated when the GDR is reachable via the initial read or via the seek fallback; absent on files where the GDR offset is beyond the read cap and the underlying fs.FS isn't seekable."},
			{"attribute_count", "int", "CDF — number of attributes (NumAttr from the GDR). Same reachability semantics as `variable_count`."},
			{"database_format", "string", "database format identifier — 'sqlite' today. Always populated when content_type starts with 'database/'. Positioned to extend over future DuckDB / PostgreSQL-dump / BoltDB additions."},
			{"sqlite_page_size", "int", "SQLite database page size in bytes — typically 4096; the spec allows 512..65536 (the 65536 case is encoded as 0x0001 in the header field and decoded transparently). Multi-GB databases sometimes use larger pages for fewer b-tree levels."},
			{"sqlite_format_version", "int", "SQLite file format write version — 1 (legacy rollback-journal) or 2 (WAL — write-ahead log). Files in WAL mode pair with a -wal sidecar that's read by the engine on next open."},
			{"sqlite_page_count", "int", "SQLite database size in pages. Multiply by `sqlite_page_size` to get the logical byte size (which may be less than the on-disk size if there's freelist space)."},
			{"sqlite_schema_version", "int", "SQLite schema cookie — incremented by SQLite on every CREATE / DROP / ALTER. Apps use this to detect 'something changed my schema since I last looked'. Distinct from `sqlite_user_version`, which apps set themselves."},
			{"sqlite_text_encoding", "string", "SQLite text encoding for TEXT columns — 'utf-8' (default and overwhelmingly the common case), 'utf-16le', or 'utf-16be'."},
			{"sqlite_user_version", "int", "SQLite `PRAGMA user_version` value — an arbitrary 32-bit integer apps use for their own schema-version tracking. Distinct from `sqlite_schema_version`."},
			{"sqlite_application_id", "int", "SQLite `PRAGMA application_id` value — a magic number apps can stamp to identify the SQLite file as theirs. Examples: 0x0FACADE0 (Mozilla Firefox places.sqlite), 0x66747261 (Fossil SCM repo)."},
			{"sqlite_application_name", "string", "Curated human-readable application name when the file matches a known stamp / filename pattern from the registry — `firefox-places`, `fossil-scm`, `chrome-history`, `chrome-cookies`, `apple-photos`, `apple-imessage`, `apple-keychain`, `macos-libcache`, plus the Chromium-family variants (edge / brave / chromium). Empty when no registry entry matches; agents can use the empty case to find unrecognised candidates for manual triage. Add new entries via a one-line struct literal in `internal/content/database_sqlite_registry.go`."},
			{"sqlite_table_count", "int", "SQLite — number of `CREATE TABLE` objects in sqlite_master. Matches `SELECT count(*) FROM sqlite_master WHERE type='table'`. Populated by the hand-rolled sqlite_master b-tree walker; v1 limitation: overflow page chains aren't followed, so VERY long CREATE statements (rare) could truncate."},
			{"sqlite_view_count", "int", "SQLite — number of `CREATE VIEW` objects in sqlite_master."},
			{"sqlite_index_count", "int", "SQLite — number of `CREATE INDEX` objects in sqlite_master. Includes auto-created indexes (`sqlite_autoindex_*`) that SQLite makes for PRIMARY KEY / UNIQUE constraints."},
			{"sqlite_trigger_count", "int", "SQLite — number of `CREATE TRIGGER` objects in sqlite_master. Useful for audit / triage; triggers often indicate change-tracking or constraint logic."},
			{"sqlite_table_names", "list<str>", "SQLite — sorted, deduplicated list of user table names from sqlite_master (capped at 100). Use `\"history\" in sqlite_table_names` to find DBs containing a known table. Auto-created index names like `sqlite_autoindex_*` don't appear here (they're counted in sqlite_index_count instead)."},
			{"sqlite_schema_fingerprint", "string", "SQLite — SHA256 hex of the sorted (type, name, sql) tuples from sqlite_master. Stable across cosmetic schema reorders; changes when CREATE statements change. Use for version detection (`sqlite_schema_fingerprint == \"<known-good>\"`) or forensic-grade schema integrity checks."},
			{"sqlite_fts_table_count", "int", "SQLite — number of FTS3 / FTS4 / FTS5 virtual tables declared in the schema. Detected by pattern-matching `CREATE VIRTUAL TABLE ... USING fts<N>` against sqlite_master rows. Useful as a precondition for full-text body extraction: `is_sqlite && sqlite_fts_table_count > 0` finds DBs worth searching with `--body`."},
			{"sqlite_fts_table_names", "list<str>", "SQLite — sorted list of FTS virtual-table names. Excludes the shadow tables (`_content`, `_idx`, `_data`, `_docsize`, `_config`) that SQLite creates alongside each FTS virtual table — those appear in `sqlite_table_names` as regular tables. Empty when the DB has no FTS tables."},
			{"sqlite_wal_format_version", "int", "SQLite WAL — file format version from the 32-byte WAL header bytes 4-7 (big-endian u32). Currently 3007000; bumped by future SQLite versions that change WAL layout. WAL sidecar only — irrelevant to main `.db` files."},
			{"sqlite_wal_page_size", "int", "SQLite WAL — database page size as recorded in the WAL header bytes 8-11 (big-endian u32). Must match the parent DB's `sqlite_page_size`; mismatch indicates a stale or corrupt WAL. Typical values 512..65536 (powers of two), default 4096."},
			{"sqlite_wal_checkpoint_seq", "int", "SQLite WAL — checkpoint sequence number from the WAL header bytes 12-15 (big-endian u32). Increments each time the WAL is checkpointed back into the main DB. Useful for forensic timelines: a high value indicates a long-lived DB with many checkpoint cycles."},
			{"sqlite_wal_frame_count", "int", "SQLite WAL — best-effort frame count, computed as `(file_size - 32) / (24 + sqlite_wal_page_size)`. Approximate when the WAL has been recently checkpointed (trailing frames may be stale). Absent when the header's page_size field is out-of-range (the sentinel for an unparseable / adversarial WAL)."},
			{"sqlite_wal_byte_order", "string", "SQLite WAL — checksum byte order, `'be'` (magic `0x377F0682`) or `'le'` (magic `0x377F0683`). Indicates the byte order used for the per-frame and per-header checksums; the header's multi-byte FIELDS are always big-endian regardless."},
			{"bookmark_count", "int", "Browser bookmark file — total count of URL bookmarks across every folder in the file. Counts ALL bookmarks (not capped); the `bookmark_urls` list is what's capped at 1000 for the JSON wire shape."},
			{"bookmark_folder_count", "int", "Browser bookmark file — total count of folder nodes (including nested folders). The Chromium / Safari conventions both flatten into the same count via the recursive walker."},
			{"bookmark_folders", "list<str>", "Browser bookmark file — sorted unique list of folder names (capped at 100). Use `'Reading List' in bookmark_folders` to find profiles with a specific folder."},
			{"bookmark_urls", "list<str>", "Browser bookmark file — all bookmark URLs (capped at 1000). Composable with `bookmark_urls.exists(u, u.matches(...))` for regex-against-URL queries."},
			{"bookmark_titles", "list<str>", "Browser bookmark file — all bookmark titles (capped at 1000). Index-aligned with `bookmark_urls` where both are non-empty."},
			{"browser_vendor", "string", "Browser bookmark file — canonical vendor short name derived from the file path: `chrome`, `chromium`, `edge`, `brave`, `opera`, `vivaldi`, `arc`, `safari`. Empty when the path doesn't match a known vendor (rare — only happens when the file is moved out of its canonical browser directory). Same path-based registry pattern as `sqlite_application_name` (#177)."},
			{"bookmark_profile", "string", "Chromium-family bookmark file — profile directory name (`Default`, `Profile 1`, `Profile 2`, etc.) parsed from the file's parent directory. Empty for Safari (single-profile-per-user)."},
			{"chat_message_count", "int", "Chat export — number of messages parsed (capped at 10000). Use `is_chat_export && chat_message_count > 100` to find busy channels."},
			{"chat_participants", "list<str>", "Chat export — distinct message authors / usernames (capped at 500). Slack uses the profile real_name / name then the user ID; Discord uses nickname then name; Signal uses sourceName then source number. Compose with `'alice' in chat_participants`."},
			{"chat_channel", "string", "Chat export — channel name. Slack: derived from the `{workspace}/{channel}/file.json` directory. Discord: the `channel.name`. Signal: the file basename (the contact)."},
			{"chat_workspace", "string", "Chat export — workspace / guild name. Slack: the grandparent directory. Discord: the `guild.name`. Empty for Signal (no workspace concept)."},
			{"chat_start_at", "timestamp", "Chat export — timestamp of the earliest message in the file. Compose with `chat_start_at > timestamp(\"2024-01-01T00:00:00Z\")`."},
			{"chat_end_at", "timestamp", "Chat export — timestamp of the latest message in the file."},
			{"font_format", "string", "Font container format: `ttf` / `otf` / `ttc` / `otc` / `woff` / `woff2`. Distinguishes the wrapper from the outline kind (`font_outline_kind`); a .otf and a .ttc could both carry CFF outlines."},
			{"font_outline_kind", "string", "Underlying glyph outline format: `truetype` (`glyf` table present), `cff` (legacy PostScript / CFF table), or `cff2` (modern CFF2). Empty when no outline table is present (rare — only happens for the bitmap-only fonts CBDT/sbix-only)."},
			{"font_family", "string", "Font family name from `name` table NameID 1 (e.g. `Inter`, `Roboto`, `SF Pro`). Decoded with the Windows-Unicode-English → Mac-Roman-English fallback priority. Also dual-surfaces to the cross-family `title` variable."},
			{"font_subfamily", "string", "Font subfamily / style from NameID 2 — `Regular`, `Bold`, `Italic`, `Bold Italic`, `Thin`, `Black`, etc. Distinct from the typographic subfamily (NameID 17) which is sometimes more specific for extended families."},
			{"font_full_name", "string", "Full font name from NameID 4 — typically `<family> <subfamily>` concatenated (e.g. `Inter Bold Italic`). Sometimes carries vendor-specific extra metadata not in the family/subfamily split."},
			{"font_version", "string", "Version string from NameID 5 — typically `Version X.Y` or `X.Y.Z`. Free-form; check `font_revision` for the typed 16.16 fixed-point version from the `head` table."},
			{"font_postscript_name", "string", "PostScript name from NameID 6 — the identifier used for font-selection via PostScript / PDF. Usually `Family-Subfamily` with hyphens (e.g. `Inter-BoldItalic`). Stable across font versions; safe for fingerprinting."},
			{"font_manufacturer", "string", "Manufacturer / vendor / foundry name from NameID 8 (e.g. `Apple`, `Google`, `Adobe`, `Type Network`)."},
			{"font_designer", "string", "Designer name from NameID 9 (e.g. `Tobias Frere-Jones`, `Erik Spiekermann`, `Robert Slimbach`). Also dual-surfaces to the cross-family `author` variable."},
			{"font_license", "string", "License description text from NameID 13. Often a paragraph of legal text (e.g. SIL Open Font License preamble, MIT-license-like terms). Truncated at 4096 bytes for sane JSON wire shape."},
			{"font_license_url", "string", "License URL from NameID 14 — typically the canonical SIL OFL link or a vendor licence page."},
			{"font_typographic_family", "string", "Typographic family from NameID 16 — the 'real' family for extended/variable families where NameID 1 has been broken into per-weight families for legacy systems (e.g. NameID 1 = `Inter Bold`, NameID 16 = `Inter`). Empty for simple families."},
			{"font_weight", "int", "Weight class from OS/2 `usWeightClass` — 100 (Thin) / 200 (ExtraLight) / 300 (Light) / 400 (Regular) / 500 (Medium) / 600 (DemiBold) / 700 (Bold) / 800 (ExtraBold) / 900 (Black). `is_bold_font` fires for >= 700."},
			{"font_width", "int", "Width class from OS/2 `usWidthClass` — 1 (UltraCondensed) through 5 (Medium / normal) to 9 (UltraExpanded)."},
			{"font_embedding", "string", "License-derived embedding permission from OS/2 `fsType`: `installable` (default — embed freely), `preview-print` (embed for preview / printing only), `editable` (embed and edit in documents), `restricted` (embed only with explicit permission). **Informational only — the format does not enforce these bits**; agents auditing font licensing should know this is a documentation field that depends on the vendor's stamping discipline."},
			{"font_panose", "string", "10-byte PANOSE classification system hex string from OS/2. PANOSE encodes family kind, serif style, weight, proportion, contrast, stroke variation, arm style, letterform, midline, x-height — a 10-byte vector intended for typeface matching. Omitted when all zeros (the 'no classification' default)."},
			{"font_unicode_ranges", "list<str>", "Unicode block names decoded from OS/2 `ulUnicodeRange1..4` (128-bit bitfield). Subset of the most-common blocks: Basic Latin, Latin-1 Supplement, Cyrillic, Greek and Coptic, Hebrew, Arabic, Devanagari, CJK Unified Ideographs, Hangul Syllables, etc. Sorted; capped at 128 entries."},
			{"font_revision", "double", "Font version from `head.fontRevision` as a Fixed-16.16 → float64 conversion. Distinct from the free-form `font_version` string (NameID 5)."},
			{"font_units_per_em", "int", "Design grid resolution from `head.unitsPerEm`. Almost always 1000 (PostScript-derived) or 2048 (TrueType-derived); modern variable fonts sometimes use 1024 or 4096."},
			{"font_mac_style", "list<str>", "Decoded bits from `head.macStyle`: `bold`, `italic`, `underline`, `outline`, `shadow`, `condensed`, `extended`. Subset of OS/2's richer styling — Apple's legacy classification."},
			{"font_italic_angle", "double", "Italic angle in degrees from `post.italicAngle` (negative = right-leaning italic, the convention). 0 for upright fonts. `is_italic_font` fires for any non-zero italic angle."},
			{"font_glyph_count", "int", "Total glyph count from `maxp.numGlyphs`. Small Latin fonts ~250; full Unicode coverage CJK fonts ~30,000+; Apple Color Emoji ~3500."},
			{"font_axis_count", "int", "Number of variable-font design axes from `fvar` table. 0 for static fonts; 1-5 for typical variable fonts (e.g. Inter has `wght` + `slnt` = 2 axes; Roboto Flex has 13)."},
			{"font_axes", "list<str>", "Variable-font axis tags from `fvar` table — `wght` (weight), `wdth` (width), `slnt` (slant), `ital` (italic), `opsz` (optical size), plus vendor-specific tags. Use `\"wght\" in font_axes` to find weight-adjustable fonts."},
			{"font_collection_count", "int", "Number of sfnt members in a TTC/OTC collection. Apple system .ttc files top out around 30; typical foundry collections ~10."},
			{"font_collection_families", "list<str>", "Sorted unique family names across all members of a TTC/OTC collection (capped at 32). The primary member's family appears in `font_family`; this list lets agents see the full membership at a glance."},
			{"woff2_total_sfnt_size", "int", "WOFF2 only — declared uncompressed sfnt size from the WOFF2 header. Useful as a 'how big would this be after extraction' triage signal."},
			{"woff2_total_compressed_size", "int", "WOFF2 only — declared compressed data block size from the WOFF2 header (excludes the 48-byte WOFF2 header itself)."},
			{"raw_kind", "string", "RAW format short name: `cr2` / `cr3` / `nef` / `arw` / `dng` / `raf` / `orf` / `rw2`. Stamped from the content-type registration, so unambiguous even when camera EXIF is missing."},
			{"raw_vendor", "string", "RAW format vendor: `canon` / `nikon` / `sony` / `adobe` / `fujifilm` / `olympus` / `panasonic`. Property of the FORMAT, not the camera — DNG always reports `adobe` regardless of which camera body produced the file."},
			{"live_photo_video_path", "string", "Absolute path to the paired Live Photo `.mov` when `is_live_photo` is true; otherwise empty. Populated only on the HEIC (image) side of the pair."},
			{"live_photo_video_size", "int", "Byte size of the paired Live Photo `.mov` when `is_live_photo` is true; otherwise zero. Cheap follow-on `os.Stat` from the sibling lookup, so available without extra cost."},
			{"live_photo_image_path", "string", "Absolute path to the paired HEIC still when `is_live_photo_video` is true; otherwise empty. Populated only on the MOV (video) side of the pair."},
			{"model3d_format", "string", "3D model format: `stl` / `obj` / `gltf`. The cross-format discriminator for the `is_3d_model` family."},
			{"vertex_count", "int", "Number of vertices in a 3D model. Binary STL reads it O(1) from the header (3 × triangle count); ASCII STL / OBJ count `vertex` / `v ` lines; glTF sums the POSITION accessor counts across mesh primitives."},
			{"face_count", "int", "Number of faces / triangles in a 3D model. STL: triangle count. OBJ: `f ` line count. glTF: indices-accessor count ÷ 3 (or POSITION ÷ 3 for non-indexed primitives). Pair with vertex_count for `is_stl && face_count < 1000000` print-friendliness checks."},
			{"has_normals", "bool", "true when the 3D model declares vertex / facet normals (STL facets always do; OBJ `vn ` lines; glTF primitive NORMAL attribute). Absence often means a mesh needs normal recomputation before rendering."},
			{"has_textures", "bool", "true when the 3D model references textures: OBJ with a `mtllib` material library, or glTF with embedded `images` / `textures`. Surfaces presence, not the texture content (extraction is out of scope)."},
			{"materials", "list", "Material names referenced by a 3D model — OBJ `usemtl` names, glTF `materials[].name`. Empty for mesh-only exports. Capped at 1024 entries."},
			{"bounding_box", "list", "Axis-aligned bounding box of a 3D model as `[minX, minY, minZ, maxX, maxY, maxZ]` (doubles). STL / OBJ accumulate it over vertex positions; glTF unions the POSITION accessors' declared min/max. Useful for printer-bed / scene-scale queries. Empty when no positions were read."},
			{"ocr_confidence", "double", "Average per-line OCR confidence (0..1) across all recognized text in an image. Populated only when `--ocr` is set AND an OCR provider is available on this platform (macOS Vision today; Linux Tesseract / Windows.Media.Ocr are future providers under the same hook). Agents can filter `ocr_confidence > 0.8` to skip noisy / handwritten content."},
			{"ocr_language", "string", "Detected dominant language of the OCR text as a BCP-47 code (e.g. `en`, `ja`, `zh-Hans`). Empty when the recognizer couldn't decide (short text, ambiguous script). macOS Vision uses `NLLanguageRecognizer` over the recognized text — same engine that powers Spotlight + Live Text."},
			{"ocr_provider", "string", "Registered provider name that produced the OCR result: `vision-macos` today. Future providers will surface their own names (`tesseract`, `win-media-ocr`) under the same attribute so agent queries against `ocr_provider == \"vision-macos\"` stay forward-compatible."},
			{"phash", "string", "16-character hex perceptual hash of an image (64-bit pHash via DCT over a 32×32 grid). Robust to mild resize / JPEG re-encode / brightness shifts. Empty unless `--with-phash` is set OR the expression references `image_similar_to(...)` (which auto-enables computation). Compare two images with `image_similar_to(reference_path, threshold)`; Hamming distance ≤ 8 ≈ 87% similar, ≤ 12 ≈ 81%, ≥ 20 likely different scenes. NOT robust to heavy cropping, rotation, or mirror flips."},
		},
		Frontmatter: []AttributeDoc{
			{"frontmatter", "map", "full parsed front-matter, e.g. frontmatter.category"},
			{"frontmatter_format", "string", "'yaml', 'toml', 'json', or '' if none"},
			{"tags", "list<str>", "front-matter tags (single string is wrapped)"},
			{"categories", "list<str>", "front-matter categories"},
			{"draft", "bool", "front-matter draft flag"},
			{"date", "timestamp", "front-matter date"},
		},
		Functions: []FunctionDoc{
			{
				Name:        "levenshtein",
				Signature:   "levenshtein(string, string) -> int",
				Description: "Edit distance (rune-aware, case-sensitive). Counts insertions, deletions, and substitutions needed to turn the first string into the second.",
				Example:     `is_audio && levenshtein(artist, "Radiohead") <= 2`,
			},
			{
				Name:        "soundex",
				Signature:   "soundex(string) -> string",
				Description: "American Soundex phonetic code (4-character ASCII, e.g. 'Robert' -> 'R163'). Useful for matching name spellings that sound alike.",
				Example:     `is_image && soundex(camera_make) == soundex("Nikon")`,
			},
			{
				Name:        "ngrams",
				Signature:   "ngrams(string, int) -> list<string>",
				Description: "Character-level n-grams of the input (sliding window, length n). Empty list when n <= 0 or n exceeds the rune length of the string.",
				Example:     `ngrams("kubernetes", 3).size() > 5`,
			},
			{
				Name:        "ngram_similarity",
				Signature:   "ngram_similarity(string, string, int) -> double",
				Description: "Jaccard similarity over character n-gram sets, ranging 0.0 (no overlap) to 1.0 (identical sets). Both empty -> 1.0; only one empty -> 0.0.",
				Example:     `is_markdown && ngram_similarity(title, "kubernetes", 2) > 0.6`,
			},
			{
				Name:        "point_in_polygon",
				Signature:   "point_in_polygon(double, double, list<double>) -> bool",
				Description: "Test whether (lat, lon) lies inside an arbitrary polygon. The third argument is a flat list of alternating lat,lon pairs: [lat0, lon0, lat1, lon1, ...]. Polygon need not be explicitly closed; planar ray-casting (good for neighbourhoods / cities / small countries).",
				Example:     `is_image && point_in_polygon(gps_lat, gps_lon, [-34.10, 18.30, -34.10, 18.50, -33.90, 18.50, -33.90, 18.30])`,
			},
			{
				Name:        "image_similar_to",
				Signature:   "image_similar_to(string, string, double) -> bool",
				Description: "True when this file's pHash (passed as the first arg, typically the `phash` CEL variable) and the reference image's pHash differ by ≤ (1 - threshold) × 64 bits (Hamming). The reference image is loaded + hashed once per process and cached. Reference path supports a leading `~/`. Pair with `--with-phash` (or any expression referencing `image_similar_to` auto-enables it) so the file's `phash` attribute is populated. Returns false when the file's phash is empty (non-image, or pHash computation hasn't run) or when the reference can't be decoded.",
				Example:     `is_image && image_similar_to(phash, "~/Pictures/reference.jpg", 0.85)`,
			},
			{
				Name:        "has_secrets",
				Signature:   "has_secrets(string) -> bool",
				Description: "True when the argument (typically the `body` variable, so requires --body / include_body) contains a credential / token / key matching the built-in catalogue: AWS access + secret keys, GitHub PATs, GitLab / Slack / Stripe / Google / npm / OpenAI tokens, PEM private keys, JWTs, credit-card numbers, and context-anchored password/secret assignments. Anchored RE2 patterns (low false-positive). Short-circuits on first match. Detection only — no validation / redaction.",
				Example:     `is_source && has_secrets(body)`,
			},
			{
				Name:        "secret_kinds",
				Signature:   "secret_kinds(string) -> list<string>",
				Description: "Returns the sorted list of secret categories matched in the argument (typically `body`): e.g. [\"aws-access-key\", \"github-token\", \"private-key-pem\"]. Empty list when none match. Companion to has_secrets when you want to know WHICH kind fired. Filter with CEL membership: `\"aws-access-key\" in secret_kinds(body)`.",
				Example:     `is_json && "private-key-pem" in secret_kinds(body)`,
			},
		},
	}
}
