package search_test

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	contentpkg "github.com/richardwooding/file-search-on/internal/content"

	"github.com/richardwooding/file-search-on/internal/search"
)

// TestComplexity_GeneratedHint pins issue #430: when generated files dominate
// the ranked output, the report carries a nudge toward !is_generated_code;
// an all-hand-written tree carries none.
func TestComplexity_GeneratedHint(t *testing.T) {
	dir := t.TempDir()
	// 4 generated Go files + 2 hand-written → 4/6 generated functions.
	for _, n := range []string{"g1", "g2", "g3", "g4"} {
		mustWriteFile(t, filepath.Join(dir, n+".go"),
			"// Code generated by test. DO NOT EDIT.\npackage p\n\nfunc "+n+"() { if true {} }\n")
	}
	for _, n := range []string{"h1", "h2"} {
		mustWriteFile(t, filepath.Join(dir, n+".go"), "package p\n\nfunc "+n+"() {}\n")
	}

	rep, err := search.Complexity(context.Background(), search.Options{Root: dir, Expr: "is_source"}, contentpkg.DefaultRegistry(), 50)
	if err != nil {
		t.Fatalf("Complexity: %v", err)
	}
	if rep.Hint == "" || !strings.Contains(rep.Hint, "is_generated_code") {
		t.Errorf("expected a generated-code hint, got %q (functions=%d)", rep.Hint, len(rep.Functions))
	}

	// Control: all hand-written → no hint.
	clean := t.TempDir()
	mustWriteFile(t, filepath.Join(clean, "a.go"), "package p\n\nfunc a() {}\nfunc b() {}\nfunc c() {}\n")
	rep2, err := search.Complexity(context.Background(), search.Options{Root: clean, Expr: "is_source"}, contentpkg.DefaultRegistry(), 50)
	if err != nil {
		t.Fatalf("Complexity(clean): %v", err)
	}
	if rep2.Hint != "" {
		t.Errorf("clean tree should have no hint, got %q", rep2.Hint)
	}
}
