package search_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/richardwooding/file-search-on/internal/content"
	"github.com/richardwooding/file-search-on/internal/search"
)

// TestWalk_IsGeneratedCode_Go is the end-to-end check for #276: a
// real Go file with the canonical `// Code generated ... DO NOT EDIT.`
// marker fires is_generated_code; a hand-written sibling doesn't.
func TestWalk_IsGeneratedCode_Go(t *testing.T) {
	dir := t.TempDir()
	generated := "// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: foo.proto\n\npackage foo\n\nfunc Marshal() {}\n"
	handWritten := "// Copyright 2026 Example Inc.\n// Apache 2.0 license header.\n\npackage foo\n\nfunc DoSomething() {}\n"

	if err := os.WriteFile(filepath.Join(dir, "generated.go"), []byte(generated), 0o644); err != nil {
		t.Fatalf("write generated: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "handwritten.go"), []byte(handWritten), 0o644); err != nil {
		t.Fatalf("write handwritten: %v", err)
	}

	// Headline #276 query: "production code only" filter excludes generated files.
	res, err := search.Walk(context.Background(), search.Options{
		Root:    dir,
		Expr:    `is_source && !is_generated_code`,
		Workers: 1,
	}, content.DefaultRegistry())
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	if len(res) != 1 {
		t.Fatalf("expected 1 match (handwritten only); got %d", len(res))
	}
	if got := filepath.Base(res[0].Path); got != "handwritten.go" {
		t.Errorf("matched %s, want handwritten.go", got)
	}

	// Inverse — find ONLY generated files.
	res2, err := search.Walk(context.Background(), search.Options{
		Root:    dir,
		Expr:    `is_source && is_generated_code`,
		Workers: 1,
	}, content.DefaultRegistry())
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	if len(res2) != 1 {
		t.Fatalf("expected 1 generated match; got %d", len(res2))
	}
	if got := filepath.Base(res2[0].Path); got != "generated.go" {
		t.Errorf("matched %s, want generated.go", got)
	}
}

// TestWalk_IsGeneratedCode_HeaderAfterCopyright confirms the
// generatedCodeLineBudget gives enough headroom: a 10-line copyright
// block FOLLOWED by the generator marker still triggers detection.
func TestWalk_IsGeneratedCode_HeaderAfterCopyright(t *testing.T) {
	dir := t.TempDir()
	body := `// Copyright 2026 Example Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS

// Code generated by buf. DO NOT EDIT.

package foo
`
	if err := os.WriteFile(filepath.Join(dir, "generated.go"), []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	res, err := search.Walk(context.Background(), search.Options{
		Root:    dir,
		Expr:    `is_generated_code`,
		Workers: 1,
	}, content.DefaultRegistry())
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	if len(res) != 1 {
		t.Errorf("expected 1 match (marker on line 11 after 10-line copyright header); got %d", len(res))
	}
}

// TestWalk_IsGeneratedCode_NoFalsePositiveOnHandWritten confirms the
// detector doesn't fire on hand-written code that happens to mention
// "generated" in comments or identifiers.
func TestWalk_IsGeneratedCode_NoFalsePositiveOnHandWritten(t *testing.T) {
	dir := t.TempDir()
	body := `// Package foo provides helpers for generated content workflows.
//
// The GenerateID function returns a random UUID. Don't edit the
// caller's session blob — copy it first.

package foo

// GenerateID returns a new ID.
func GenerateID() string { return "" }
`
	if err := os.WriteFile(filepath.Join(dir, "foo.go"), []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	res, err := search.Walk(context.Background(), search.Options{
		Root:    dir,
		Expr:    `is_generated_code`,
		Workers: 1,
	}, content.DefaultRegistry())
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	if len(res) != 0 {
		t.Errorf("hand-written file with 'generated' in prose should NOT fire is_generated_code; got %d match(es)", len(res))
	}
}

// TestWalk_IsGeneratedCode_Python catches that the per-language wiring
// works for Python too, not just Go.
func TestWalk_IsGeneratedCode_Python(t *testing.T) {
	dir := t.TempDir()
	body := "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n# source: foo.proto\n\nfrom google.protobuf import descriptor as _descriptor\n"
	if err := os.WriteFile(filepath.Join(dir, "foo_pb2.py"), []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	res, err := search.Walk(context.Background(), search.Options{
		Root:    dir,
		Expr:    `is_source && language == "python" && is_generated_code`,
		Workers: 1,
	}, content.DefaultRegistry())
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}
	if len(res) != 1 {
		t.Errorf("python generated file not detected; got %d match(es)", len(res))
	}
}
